// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: chat/v1/chat.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationChatServiceCreateFeedback = "/chat.v1.ChatService/CreateFeedback"
const OperationChatServiceCreateSession = "/chat.v1.ChatService/CreateSession"
const OperationChatServiceDeleteSession = "/chat.v1.ChatService/DeleteSession"
const OperationChatServiceGetSession = "/chat.v1.ChatService/GetSession"
const OperationChatServiceListMessages = "/chat.v1.ChatService/ListMessages"
const OperationChatServiceListSessions = "/chat.v1.ChatService/ListSessions"
const OperationChatServiceSendMessage = "/chat.v1.ChatService/SendMessage"
const OperationChatServiceSummarizeSession = "/chat.v1.ChatService/SummarizeSession"
const OperationChatServiceUpdateSession = "/chat.v1.ChatService/UpdateSession"

type ChatServiceHTTPServer interface {
	// CreateFeedback 提交对某条 AI 回复的评分和反馈。
	CreateFeedback(context.Context, *CreateFeedbackRequest) (*ChatFeedback, error)
	// CreateSession 创建 AI 情感咨询会话。
	CreateSession(context.Context, *CreateSessionRequest) (*ChatSession, error)
	// DeleteSession 删除当前用户指定咨询会话。
	DeleteSession(context.Context, *DeleteSessionRequest) (*emptypb.Empty, error)
	// GetSession 获取当前用户指定咨询会话详情。
	GetSession(context.Context, *GetSessionRequest) (*ChatSession, error)
	// ListMessages 分页查询指定咨询会话下的聊天消息。
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	// ListSessions 分页查询当前用户的历史咨询会话。
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// SendMessage 发送用户消息，触发 AI 回复，并保存双方消息。
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// SummarizeSession 生成并保存指定咨询会话的上下文摘要。
	SummarizeSession(context.Context, *SummarizeSessionRequest) (*ChatContextSummary, error)
	// UpdateSession 修改咨询会话标题或状态。
	UpdateSession(context.Context, *UpdateSessionRequest) (*ChatSession, error)
}

func RegisterChatServiceHTTPServer(s *http.Server, srv ChatServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/chat/sessions", _ChatService_CreateSession0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/chat/sessions", _ChatService_ListSessions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/chat/sessions/{id}", _ChatService_GetSession0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/chat/sessions/{id}", _ChatService_UpdateSession0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/chat/sessions/{id}", _ChatService_DeleteSession0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/chat/sessions/{session_id}/messages", _ChatService_ListMessages0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/chat/sessions/{session_id}/messages", _ChatService_SendMessage0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/chat/messages/{message_id}/feedback", _ChatService_CreateFeedback0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/chat/sessions/{session_id}/summarize", _ChatService_SummarizeSession0_HTTP_Handler(srv))
}

func _ChatService_CreateSession0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceCreateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSession(ctx, req.(*CreateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatSession)
		return ctx.Result(200, reply)
	}
}

func _ChatService_ListSessions0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*ListSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionsResponse)
		return ctx.Result(200, reply)
	}
}

func _ChatService_GetSession0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceGetSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSession(ctx, req.(*GetSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatSession)
		return ctx.Result(200, reply)
	}
}

func _ChatService_UpdateSession0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceUpdateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSession(ctx, req.(*UpdateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatSession)
		return ctx.Result(200, reply)
	}
}

func _ChatService_DeleteSession0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceDeleteSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSession(ctx, req.(*DeleteSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ChatService_ListMessages0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _ChatService_SendMessage0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageResponse)
		return ctx.Result(200, reply)
	}
}

func _ChatService_CreateFeedback0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateFeedbackRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceCreateFeedback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFeedback(ctx, req.(*CreateFeedbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatFeedback)
		return ctx.Result(200, reply)
	}
}

func _ChatService_SummarizeSession0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SummarizeSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceSummarizeSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SummarizeSession(ctx, req.(*SummarizeSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatContextSummary)
		return ctx.Result(200, reply)
	}
}

type ChatServiceHTTPClient interface {
	// CreateFeedback 提交对某条 AI 回复的评分和反馈。
	CreateFeedback(ctx context.Context, req *CreateFeedbackRequest, opts ...http.CallOption) (rsp *ChatFeedback, err error)
	// CreateSession 创建 AI 情感咨询会话。
	CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...http.CallOption) (rsp *ChatSession, err error)
	// DeleteSession 删除当前用户指定咨询会话。
	DeleteSession(ctx context.Context, req *DeleteSessionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetSession 获取当前用户指定咨询会话详情。
	GetSession(ctx context.Context, req *GetSessionRequest, opts ...http.CallOption) (rsp *ChatSession, err error)
	// ListMessages 分页查询指定咨询会话下的聊天消息。
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *ListMessagesResponse, err error)
	// ListSessions 分页查询当前用户的历史咨询会话。
	ListSessions(ctx context.Context, req *ListSessionsRequest, opts ...http.CallOption) (rsp *ListSessionsResponse, err error)
	// SendMessage 发送用户消息，触发 AI 回复，并保存双方消息。
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageResponse, err error)
	// SummarizeSession 生成并保存指定咨询会话的上下文摘要。
	SummarizeSession(ctx context.Context, req *SummarizeSessionRequest, opts ...http.CallOption) (rsp *ChatContextSummary, err error)
	// UpdateSession 修改咨询会话标题或状态。
	UpdateSession(ctx context.Context, req *UpdateSessionRequest, opts ...http.CallOption) (rsp *ChatSession, err error)
}

type ChatServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewChatServiceHTTPClient(client *http.Client) ChatServiceHTTPClient {
	return &ChatServiceHTTPClientImpl{client}
}

// CreateFeedback 提交对某条 AI 回复的评分和反馈。
func (c *ChatServiceHTTPClientImpl) CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...http.CallOption) (*ChatFeedback, error) {
	var out ChatFeedback
	pattern := "/v1/chat/messages/{message_id}/feedback"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChatServiceCreateFeedback),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSession 创建 AI 情感咨询会话。
func (c *ChatServiceHTTPClientImpl) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...http.CallOption) (*ChatSession, error) {
	var out ChatSession
	pattern := "/v1/chat/sessions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChatServiceCreateSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSession 删除当前用户指定咨询会话。
func (c *ChatServiceHTTPClientImpl) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/chat/sessions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChatServiceDeleteSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSession 获取当前用户指定咨询会话详情。
func (c *ChatServiceHTTPClientImpl) GetSession(ctx context.Context, in *GetSessionRequest, opts ...http.CallOption) (*ChatSession, error) {
	var out ChatSession
	pattern := "/v1/chat/sessions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChatServiceGetSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMessages 分页查询指定咨询会话下的聊天消息。
func (c *ChatServiceHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*ListMessagesResponse, error) {
	var out ListMessagesResponse
	pattern := "/v1/chat/sessions/{session_id}/messages"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChatServiceListMessages),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSessions 分页查询当前用户的历史咨询会话。
func (c *ChatServiceHTTPClientImpl) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...http.CallOption) (*ListSessionsResponse, error) {
	var out ListSessionsResponse
	pattern := "/v1/chat/sessions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationChatServiceListSessions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendMessage 发送用户消息，触发 AI 回复，并保存双方消息。
func (c *ChatServiceHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageResponse, error) {
	var out SendMessageResponse
	pattern := "/v1/chat/sessions/{session_id}/messages"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChatServiceSendMessage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SummarizeSession 生成并保存指定咨询会话的上下文摘要。
func (c *ChatServiceHTTPClientImpl) SummarizeSession(ctx context.Context, in *SummarizeSessionRequest, opts ...http.CallOption) (*ChatContextSummary, error) {
	var out ChatContextSummary
	pattern := "/v1/chat/sessions/{session_id}/summarize"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChatServiceSummarizeSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSession 修改咨询会话标题或状态。
func (c *ChatServiceHTTPClientImpl) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...http.CallOption) (*ChatSession, error) {
	var out ChatSession
	pattern := "/v1/chat/sessions/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationChatServiceUpdateSession),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
