// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: admin/v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAdminServiceCreateAnnouncement = "/admin.v1.AdminService/CreateAnnouncement"
const OperationAdminServiceCreateAppVersion = "/admin.v1.AdminService/CreateAppVersion"
const OperationAdminServiceCreateMoodTag = "/admin.v1.AdminService/CreateMoodTag"
const OperationAdminServiceCreateSystemConfig = "/admin.v1.AdminService/CreateSystemConfig"
const OperationAdminServiceDeleteAnnouncement = "/admin.v1.AdminService/DeleteAnnouncement"
const OperationAdminServiceDeleteAppVersion = "/admin.v1.AdminService/DeleteAppVersion"
const OperationAdminServiceDeleteDiary = "/admin.v1.AdminService/DeleteDiary"
const OperationAdminServiceDeleteFile = "/admin.v1.AdminService/DeleteFile"
const OperationAdminServiceDeleteMoodTag = "/admin.v1.AdminService/DeleteMoodTag"
const OperationAdminServiceDeleteSystemConfig = "/admin.v1.AdminService/DeleteSystemConfig"
const OperationAdminServiceGetDashboardOverview = "/admin.v1.AdminService/GetDashboardOverview"
const OperationAdminServiceGetDashboardTrends = "/admin.v1.AdminService/GetDashboardTrends"
const OperationAdminServiceGetDiary = "/admin.v1.AdminService/GetDiary"
const OperationAdminServiceGetEmotionAnalysis = "/admin.v1.AdminService/GetEmotionAnalysis"
const OperationAdminServiceGetFile = "/admin.v1.AdminService/GetFile"
const OperationAdminServiceGetUser = "/admin.v1.AdminService/GetUser"
const OperationAdminServiceListAnnouncements = "/admin.v1.AdminService/ListAnnouncements"
const OperationAdminServiceListAppVersions = "/admin.v1.AdminService/ListAppVersions"
const OperationAdminServiceListChatMessages = "/admin.v1.AdminService/ListChatMessages"
const OperationAdminServiceListChatSessions = "/admin.v1.AdminService/ListChatSessions"
const OperationAdminServiceListDiaries = "/admin.v1.AdminService/ListDiaries"
const OperationAdminServiceListEmotionAnalyses = "/admin.v1.AdminService/ListEmotionAnalyses"
const OperationAdminServiceListFiles = "/admin.v1.AdminService/ListFiles"
const OperationAdminServiceListMoodTags = "/admin.v1.AdminService/ListMoodTags"
const OperationAdminServiceListSystemConfigs = "/admin.v1.AdminService/ListSystemConfigs"
const OperationAdminServiceListUsers = "/admin.v1.AdminService/ListUsers"
const OperationAdminServiceUpdateAnnouncement = "/admin.v1.AdminService/UpdateAnnouncement"
const OperationAdminServiceUpdateAppVersion = "/admin.v1.AdminService/UpdateAppVersion"
const OperationAdminServiceUpdateMoodTag = "/admin.v1.AdminService/UpdateMoodTag"
const OperationAdminServiceUpdateSystemConfig = "/admin.v1.AdminService/UpdateSystemConfig"
const OperationAdminServiceUpdateUserRoles = "/admin.v1.AdminService/UpdateUserRoles"
const OperationAdminServiceUpdateUserStatus = "/admin.v1.AdminService/UpdateUserStatus"

type AdminServiceHTTPServer interface {
	CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*SystemAnnouncement, error)
	CreateAppVersion(context.Context, *CreateAppVersionRequest) (*AppVersion, error)
	CreateMoodTag(context.Context, *CreateMoodTagRequest) (*MoodTag, error)
	CreateSystemConfig(context.Context, *CreateSystemConfigRequest) (*SystemConfig, error)
	DeleteAnnouncement(context.Context, *DeleteAnnouncementRequest) (*emptypb.Empty, error)
	DeleteAppVersion(context.Context, *DeleteAppVersionRequest) (*emptypb.Empty, error)
	DeleteDiary(context.Context, *DeleteAdminDiaryRequest) (*emptypb.Empty, error)
	DeleteFile(context.Context, *DeleteAdminFileRequest) (*emptypb.Empty, error)
	DeleteMoodTag(context.Context, *DeleteMoodTagRequest) (*emptypb.Empty, error)
	DeleteSystemConfig(context.Context, *DeleteSystemConfigRequest) (*emptypb.Empty, error)
	GetDashboardOverview(context.Context, *GetDashboardOverviewRequest) (*DashboardOverview, error)
	GetDashboardTrends(context.Context, *GetDashboardTrendsRequest) (*DashboardTrends, error)
	GetDiary(context.Context, *GetAdminDiaryRequest) (*AdminDiary, error)
	GetEmotionAnalysis(context.Context, *GetAdminEmotionAnalysisRequest) (*AdminEmotionAnalysis, error)
	GetFile(context.Context, *GetAdminFileRequest) (*AdminFileAsset, error)
	GetUser(context.Context, *GetUserRequest) (*AdminUserDetail, error)
	ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error)
	ListAppVersions(context.Context, *ListAppVersionsRequest) (*ListAppVersionsResponse, error)
	ListChatMessages(context.Context, *ListAdminChatMessagesRequest) (*ListAdminChatMessagesResponse, error)
	ListChatSessions(context.Context, *ListAdminChatSessionsRequest) (*ListAdminChatSessionsResponse, error)
	ListDiaries(context.Context, *ListAdminDiariesRequest) (*ListAdminDiariesResponse, error)
	ListEmotionAnalyses(context.Context, *ListAdminEmotionAnalysesRequest) (*ListAdminEmotionAnalysesResponse, error)
	ListFiles(context.Context, *ListAdminFilesRequest) (*ListAdminFilesResponse, error)
	ListMoodTags(context.Context, *ListMoodTagsRequest) (*ListMoodTagsResponse, error)
	ListSystemConfigs(context.Context, *ListSystemConfigsRequest) (*ListSystemConfigsResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UpdateAnnouncement(context.Context, *UpdateAnnouncementRequest) (*SystemAnnouncement, error)
	UpdateAppVersion(context.Context, *UpdateAppVersionRequest) (*AppVersion, error)
	UpdateMoodTag(context.Context, *UpdateMoodTagRequest) (*MoodTag, error)
	UpdateSystemConfig(context.Context, *UpdateSystemConfigRequest) (*SystemConfig, error)
	UpdateUserRoles(context.Context, *UpdateUserRolesRequest) (*AdminUser, error)
	UpdateUserStatus(context.Context, *UpdateUserStatusRequest) (*AdminUser, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/admin/dashboard/overview", _AdminService_GetDashboardOverview0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/dashboard/trends", _AdminService_GetDashboardTrends0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/users", _AdminService_ListUsers0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/users/{user_id}", _AdminService_GetUser0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/users/{user_id}/status", _AdminService_UpdateUserStatus0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/users/{user_id}/roles", _AdminService_UpdateUserRoles0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/system/configs", _AdminService_ListSystemConfigs0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/system/configs", _AdminService_CreateSystemConfig0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/system/configs/{id}", _AdminService_UpdateSystemConfig0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/system/configs/{id}", _AdminService_DeleteSystemConfig0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/system/announcements", _AdminService_ListAnnouncements0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/system/announcements", _AdminService_CreateAnnouncement0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/system/announcements/{id}", _AdminService_UpdateAnnouncement0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/system/announcements/{id}", _AdminService_DeleteAnnouncement0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/system/versions", _AdminService_ListAppVersions0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/system/versions", _AdminService_CreateAppVersion0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/system/versions/{id}", _AdminService_UpdateAppVersion0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/system/versions/{id}", _AdminService_DeleteAppVersion0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/mood-tags", _AdminService_ListMoodTags0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/mood-tags", _AdminService_CreateMoodTag0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/mood-tags/{id}", _AdminService_UpdateMoodTag0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/mood-tags/{id}", _AdminService_DeleteMoodTag0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/diaries", _AdminService_ListDiaries0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/diaries/{id}", _AdminService_GetDiary0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/diaries/{id}", _AdminService_DeleteDiary0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/emotion/analyses", _AdminService_ListEmotionAnalyses0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/emotion/analyses/{id}", _AdminService_GetEmotionAnalysis0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/chat/sessions", _AdminService_ListChatSessions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/chat/sessions/{session_id}/messages", _AdminService_ListChatMessages0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/files", _AdminService_ListFiles0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/files/{id}", _AdminService_GetFile0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/files/{id}", _AdminService_DeleteFile0_HTTP_Handler(srv))
}

func _AdminService_GetDashboardOverview0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDashboardOverviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetDashboardOverview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDashboardOverview(ctx, req.(*GetDashboardOverviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DashboardOverview)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetDashboardTrends0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDashboardTrendsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetDashboardTrends)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDashboardTrends(ctx, req.(*GetDashboardTrendsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DashboardTrends)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListUsers0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetUser0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminUserDetail)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateUserStatus0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateUserStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserStatus(ctx, req.(*UpdateUserStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminUser)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateUserRoles0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserRolesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateUserRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserRoles(ctx, req.(*UpdateUserRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminUser)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListSystemConfigs0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSystemConfigsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListSystemConfigs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSystemConfigs(ctx, req.(*ListSystemConfigsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSystemConfigsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateSystemConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSystemConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateSystemConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSystemConfig(ctx, req.(*CreateSystemConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemConfig)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateSystemConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSystemConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateSystemConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSystemConfig(ctx, req.(*UpdateSystemConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemConfig)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteSystemConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSystemConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteSystemConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSystemConfig(ctx, req.(*DeleteSystemConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListAnnouncements0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAnnouncementsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListAnnouncements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAnnouncements(ctx, req.(*ListAnnouncementsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAnnouncementsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateAnnouncement0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAnnouncementRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateAnnouncement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAnnouncement(ctx, req.(*CreateAnnouncementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemAnnouncement)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateAnnouncement0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAnnouncementRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateAnnouncement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAnnouncement(ctx, req.(*UpdateAnnouncementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemAnnouncement)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteAnnouncement0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAnnouncementRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteAnnouncement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAnnouncement(ctx, req.(*DeleteAnnouncementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListAppVersions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAppVersionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListAppVersions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAppVersions(ctx, req.(*ListAppVersionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAppVersionsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateAppVersion0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAppVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateAppVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAppVersion(ctx, req.(*CreateAppVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppVersion)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateAppVersion0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAppVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateAppVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAppVersion(ctx, req.(*UpdateAppVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppVersion)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteAppVersion0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAppVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteAppVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAppVersion(ctx, req.(*DeleteAppVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListMoodTags0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMoodTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListMoodTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMoodTags(ctx, req.(*ListMoodTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMoodTagsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateMoodTag0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMoodTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateMoodTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMoodTag(ctx, req.(*CreateMoodTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoodTag)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateMoodTag0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMoodTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateMoodTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMoodTag(ctx, req.(*UpdateMoodTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoodTag)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteMoodTag0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMoodTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteMoodTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMoodTag(ctx, req.(*DeleteMoodTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListDiaries0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminDiariesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListDiaries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDiaries(ctx, req.(*ListAdminDiariesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAdminDiariesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetDiary0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAdminDiaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDiary(ctx, req.(*GetAdminDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminDiary)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteDiary0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAdminDiaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDiary(ctx, req.(*DeleteAdminDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListEmotionAnalyses0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminEmotionAnalysesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListEmotionAnalyses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEmotionAnalyses(ctx, req.(*ListAdminEmotionAnalysesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAdminEmotionAnalysesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetEmotionAnalysis0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAdminEmotionAnalysisRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetEmotionAnalysis)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmotionAnalysis(ctx, req.(*GetAdminEmotionAnalysisRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminEmotionAnalysis)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListChatSessions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminChatSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListChatSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChatSessions(ctx, req.(*ListAdminChatSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAdminChatSessionsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListChatMessages0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminChatMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListChatMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChatMessages(ctx, req.(*ListAdminChatMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAdminChatMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListFiles0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminFilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFiles(ctx, req.(*ListAdminFilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAdminFilesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetFile0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAdminFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFile(ctx, req.(*GetAdminFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminFileAsset)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteFile0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAdminFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteFile(ctx, req.(*DeleteAdminFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	CreateAnnouncement(ctx context.Context, req *CreateAnnouncementRequest, opts ...http.CallOption) (rsp *SystemAnnouncement, err error)
	CreateAppVersion(ctx context.Context, req *CreateAppVersionRequest, opts ...http.CallOption) (rsp *AppVersion, err error)
	CreateMoodTag(ctx context.Context, req *CreateMoodTagRequest, opts ...http.CallOption) (rsp *MoodTag, err error)
	CreateSystemConfig(ctx context.Context, req *CreateSystemConfigRequest, opts ...http.CallOption) (rsp *SystemConfig, err error)
	DeleteAnnouncement(ctx context.Context, req *DeleteAnnouncementRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteAppVersion(ctx context.Context, req *DeleteAppVersionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteDiary(ctx context.Context, req *DeleteAdminDiaryRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteFile(ctx context.Context, req *DeleteAdminFileRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteMoodTag(ctx context.Context, req *DeleteMoodTagRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteSystemConfig(ctx context.Context, req *DeleteSystemConfigRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetDashboardOverview(ctx context.Context, req *GetDashboardOverviewRequest, opts ...http.CallOption) (rsp *DashboardOverview, err error)
	GetDashboardTrends(ctx context.Context, req *GetDashboardTrendsRequest, opts ...http.CallOption) (rsp *DashboardTrends, err error)
	GetDiary(ctx context.Context, req *GetAdminDiaryRequest, opts ...http.CallOption) (rsp *AdminDiary, err error)
	GetEmotionAnalysis(ctx context.Context, req *GetAdminEmotionAnalysisRequest, opts ...http.CallOption) (rsp *AdminEmotionAnalysis, err error)
	GetFile(ctx context.Context, req *GetAdminFileRequest, opts ...http.CallOption) (rsp *AdminFileAsset, err error)
	GetUser(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *AdminUserDetail, err error)
	ListAnnouncements(ctx context.Context, req *ListAnnouncementsRequest, opts ...http.CallOption) (rsp *ListAnnouncementsResponse, err error)
	ListAppVersions(ctx context.Context, req *ListAppVersionsRequest, opts ...http.CallOption) (rsp *ListAppVersionsResponse, err error)
	ListChatMessages(ctx context.Context, req *ListAdminChatMessagesRequest, opts ...http.CallOption) (rsp *ListAdminChatMessagesResponse, err error)
	ListChatSessions(ctx context.Context, req *ListAdminChatSessionsRequest, opts ...http.CallOption) (rsp *ListAdminChatSessionsResponse, err error)
	ListDiaries(ctx context.Context, req *ListAdminDiariesRequest, opts ...http.CallOption) (rsp *ListAdminDiariesResponse, err error)
	ListEmotionAnalyses(ctx context.Context, req *ListAdminEmotionAnalysesRequest, opts ...http.CallOption) (rsp *ListAdminEmotionAnalysesResponse, err error)
	ListFiles(ctx context.Context, req *ListAdminFilesRequest, opts ...http.CallOption) (rsp *ListAdminFilesResponse, err error)
	ListMoodTags(ctx context.Context, req *ListMoodTagsRequest, opts ...http.CallOption) (rsp *ListMoodTagsResponse, err error)
	ListSystemConfigs(ctx context.Context, req *ListSystemConfigsRequest, opts ...http.CallOption) (rsp *ListSystemConfigsResponse, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...http.CallOption) (rsp *ListUsersResponse, err error)
	UpdateAnnouncement(ctx context.Context, req *UpdateAnnouncementRequest, opts ...http.CallOption) (rsp *SystemAnnouncement, err error)
	UpdateAppVersion(ctx context.Context, req *UpdateAppVersionRequest, opts ...http.CallOption) (rsp *AppVersion, err error)
	UpdateMoodTag(ctx context.Context, req *UpdateMoodTagRequest, opts ...http.CallOption) (rsp *MoodTag, err error)
	UpdateSystemConfig(ctx context.Context, req *UpdateSystemConfigRequest, opts ...http.CallOption) (rsp *SystemConfig, err error)
	UpdateUserRoles(ctx context.Context, req *UpdateUserRolesRequest, opts ...http.CallOption) (rsp *AdminUser, err error)
	UpdateUserStatus(ctx context.Context, req *UpdateUserStatusRequest, opts ...http.CallOption) (rsp *AdminUser, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

func (c *AdminServiceHTTPClientImpl) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...http.CallOption) (*SystemAnnouncement, error) {
	var out SystemAnnouncement
	pattern := "/v1/admin/system/announcements"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateAnnouncement),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateAppVersion(ctx context.Context, in *CreateAppVersionRequest, opts ...http.CallOption) (*AppVersion, error) {
	var out AppVersion
	pattern := "/v1/admin/system/versions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateAppVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateMoodTag(ctx context.Context, in *CreateMoodTagRequest, opts ...http.CallOption) (*MoodTag, error) {
	var out MoodTag
	pattern := "/v1/admin/mood-tags"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateMoodTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateSystemConfig(ctx context.Context, in *CreateSystemConfigRequest, opts ...http.CallOption) (*SystemConfig, error) {
	var out SystemConfig
	pattern := "/v1/admin/system/configs"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateSystemConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/system/announcements/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteAnnouncement),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteAppVersion(ctx context.Context, in *DeleteAppVersionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/system/versions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteAppVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteDiary(ctx context.Context, in *DeleteAdminDiaryRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/diaries/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteFile(ctx context.Context, in *DeleteAdminFileRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/files/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteMoodTag(ctx context.Context, in *DeleteMoodTagRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/mood-tags/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteMoodTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteSystemConfig(ctx context.Context, in *DeleteSystemConfigRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/system/configs/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteSystemConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetDashboardOverview(ctx context.Context, in *GetDashboardOverviewRequest, opts ...http.CallOption) (*DashboardOverview, error) {
	var out DashboardOverview
	pattern := "/v1/admin/dashboard/overview"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetDashboardOverview),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetDashboardTrends(ctx context.Context, in *GetDashboardTrendsRequest, opts ...http.CallOption) (*DashboardTrends, error) {
	var out DashboardTrends
	pattern := "/v1/admin/dashboard/trends"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetDashboardTrends),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetDiary(ctx context.Context, in *GetAdminDiaryRequest, opts ...http.CallOption) (*AdminDiary, error) {
	var out AdminDiary
	pattern := "/v1/admin/diaries/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetEmotionAnalysis(ctx context.Context, in *GetAdminEmotionAnalysisRequest, opts ...http.CallOption) (*AdminEmotionAnalysis, error) {
	var out AdminEmotionAnalysis
	pattern := "/v1/admin/emotion/analyses/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetEmotionAnalysis),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetFile(ctx context.Context, in *GetAdminFileRequest, opts ...http.CallOption) (*AdminFileAsset, error) {
	var out AdminFileAsset
	pattern := "/v1/admin/files/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*AdminUserDetail, error) {
	var out AdminUserDetail
	pattern := "/v1/admin/users/{user_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...http.CallOption) (*ListAnnouncementsResponse, error) {
	var out ListAnnouncementsResponse
	pattern := "/v1/admin/system/announcements"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListAnnouncements),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListAppVersions(ctx context.Context, in *ListAppVersionsRequest, opts ...http.CallOption) (*ListAppVersionsResponse, error) {
	var out ListAppVersionsResponse
	pattern := "/v1/admin/system/versions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListAppVersions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListChatMessages(ctx context.Context, in *ListAdminChatMessagesRequest, opts ...http.CallOption) (*ListAdminChatMessagesResponse, error) {
	var out ListAdminChatMessagesResponse
	pattern := "/v1/admin/chat/sessions/{session_id}/messages"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListChatMessages),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListChatSessions(ctx context.Context, in *ListAdminChatSessionsRequest, opts ...http.CallOption) (*ListAdminChatSessionsResponse, error) {
	var out ListAdminChatSessionsResponse
	pattern := "/v1/admin/chat/sessions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListChatSessions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListDiaries(ctx context.Context, in *ListAdminDiariesRequest, opts ...http.CallOption) (*ListAdminDiariesResponse, error) {
	var out ListAdminDiariesResponse
	pattern := "/v1/admin/diaries"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListDiaries),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListEmotionAnalyses(ctx context.Context, in *ListAdminEmotionAnalysesRequest, opts ...http.CallOption) (*ListAdminEmotionAnalysesResponse, error) {
	var out ListAdminEmotionAnalysesResponse
	pattern := "/v1/admin/emotion/analyses"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListEmotionAnalyses),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListFiles(ctx context.Context, in *ListAdminFilesRequest, opts ...http.CallOption) (*ListAdminFilesResponse, error) {
	var out ListAdminFilesResponse
	pattern := "/v1/admin/files"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListFiles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListMoodTags(ctx context.Context, in *ListMoodTagsRequest, opts ...http.CallOption) (*ListMoodTagsResponse, error) {
	var out ListMoodTagsResponse
	pattern := "/v1/admin/mood-tags"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListMoodTags),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListSystemConfigs(ctx context.Context, in *ListSystemConfigsRequest, opts ...http.CallOption) (*ListSystemConfigsResponse, error) {
	var out ListSystemConfigsResponse
	pattern := "/v1/admin/system/configs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListSystemConfigs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...http.CallOption) (*ListUsersResponse, error) {
	var out ListUsersResponse
	pattern := "/v1/admin/users"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListUsers),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateAnnouncement(ctx context.Context, in *UpdateAnnouncementRequest, opts ...http.CallOption) (*SystemAnnouncement, error) {
	var out SystemAnnouncement
	pattern := "/v1/admin/system/announcements/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateAnnouncement),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateAppVersion(ctx context.Context, in *UpdateAppVersionRequest, opts ...http.CallOption) (*AppVersion, error) {
	var out AppVersion
	pattern := "/v1/admin/system/versions/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateAppVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateMoodTag(ctx context.Context, in *UpdateMoodTagRequest, opts ...http.CallOption) (*MoodTag, error) {
	var out MoodTag
	pattern := "/v1/admin/mood-tags/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateMoodTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateSystemConfig(ctx context.Context, in *UpdateSystemConfigRequest, opts ...http.CallOption) (*SystemConfig, error) {
	var out SystemConfig
	pattern := "/v1/admin/system/configs/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateSystemConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateUserRoles(ctx context.Context, in *UpdateUserRolesRequest, opts ...http.CallOption) (*AdminUser, error) {
	var out AdminUser
	pattern := "/v1/admin/users/{user_id}/roles"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateUserRoles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...http.CallOption) (*AdminUser, error) {
	var out AdminUser
	pattern := "/v1/admin/users/{user_id}/status"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateUserStatus),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
