// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: admin/v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAdminServiceCreateAnnouncement = "/admin.v1.AdminService/CreateAnnouncement"
const OperationAdminServiceCreateConfig = "/admin.v1.AdminService/CreateConfig"
const OperationAdminServiceCreateMoodTag = "/admin.v1.AdminService/CreateMoodTag"
const OperationAdminServiceCreateVersion = "/admin.v1.AdminService/CreateVersion"
const OperationAdminServiceDeleteAnnouncement = "/admin.v1.AdminService/DeleteAnnouncement"
const OperationAdminServiceDeleteConfig = "/admin.v1.AdminService/DeleteConfig"
const OperationAdminServiceDeleteDiary = "/admin.v1.AdminService/DeleteDiary"
const OperationAdminServiceDeleteFile = "/admin.v1.AdminService/DeleteFile"
const OperationAdminServiceDeleteMoodTag = "/admin.v1.AdminService/DeleteMoodTag"
const OperationAdminServiceDeleteVersion = "/admin.v1.AdminService/DeleteVersion"
const OperationAdminServiceGetDashboardOverview = "/admin.v1.AdminService/GetDashboardOverview"
const OperationAdminServiceGetDashboardTrends = "/admin.v1.AdminService/GetDashboardTrends"
const OperationAdminServiceGetDiary = "/admin.v1.AdminService/GetDiary"
const OperationAdminServiceGetEmotionAnalysis = "/admin.v1.AdminService/GetEmotionAnalysis"
const OperationAdminServiceGetFile = "/admin.v1.AdminService/GetFile"
const OperationAdminServiceGetUser = "/admin.v1.AdminService/GetUser"
const OperationAdminServiceListAnnouncements = "/admin.v1.AdminService/ListAnnouncements"
const OperationAdminServiceListChatMessages = "/admin.v1.AdminService/ListChatMessages"
const OperationAdminServiceListChatSessions = "/admin.v1.AdminService/ListChatSessions"
const OperationAdminServiceListConfigs = "/admin.v1.AdminService/ListConfigs"
const OperationAdminServiceListDiaries = "/admin.v1.AdminService/ListDiaries"
const OperationAdminServiceListEmotionAnalyses = "/admin.v1.AdminService/ListEmotionAnalyses"
const OperationAdminServiceListFiles = "/admin.v1.AdminService/ListFiles"
const OperationAdminServiceListLoginLogs = "/admin.v1.AdminService/ListLoginLogs"
const OperationAdminServiceListMoodTags = "/admin.v1.AdminService/ListMoodTags"
const OperationAdminServiceListSecurityEvents = "/admin.v1.AdminService/ListSecurityEvents"
const OperationAdminServiceListUsers = "/admin.v1.AdminService/ListUsers"
const OperationAdminServiceListVersions = "/admin.v1.AdminService/ListVersions"
const OperationAdminServiceUpdateAnnouncement = "/admin.v1.AdminService/UpdateAnnouncement"
const OperationAdminServiceUpdateConfig = "/admin.v1.AdminService/UpdateConfig"
const OperationAdminServiceUpdateMoodTag = "/admin.v1.AdminService/UpdateMoodTag"
const OperationAdminServiceUpdateUserPassword = "/admin.v1.AdminService/UpdateUserPassword"
const OperationAdminServiceUpdateUserRoles = "/admin.v1.AdminService/UpdateUserRoles"
const OperationAdminServiceUpdateUserStatus = "/admin.v1.AdminService/UpdateUserStatus"
const OperationAdminServiceUpdateVersion = "/admin.v1.AdminService/UpdateVersion"

type AdminServiceHTTPServer interface {
	CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*AdminAnnouncement, error)
	CreateConfig(context.Context, *CreateConfigRequest) (*AdminSystemConfig, error)
	CreateMoodTag(context.Context, *CreateMoodTagRequest) (*AdminMoodTag, error)
	CreateVersion(context.Context, *CreateVersionRequest) (*AdminAppVersion, error)
	DeleteAnnouncement(context.Context, *DeleteAnnouncementRequest) (*emptypb.Empty, error)
	DeleteConfig(context.Context, *DeleteConfigRequest) (*emptypb.Empty, error)
	DeleteDiary(context.Context, *DeleteDiaryRequest) (*emptypb.Empty, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*emptypb.Empty, error)
	DeleteMoodTag(context.Context, *DeleteMoodTagRequest) (*emptypb.Empty, error)
	DeleteVersion(context.Context, *DeleteVersionRequest) (*emptypb.Empty, error)
	GetDashboardOverview(context.Context, *GetDashboardOverviewRequest) (*DashboardOverview, error)
	GetDashboardTrends(context.Context, *GetDashboardTrendsRequest) (*DashboardTrends, error)
	GetDiary(context.Context, *GetDiaryRequest) (*AdminDiary, error)
	GetEmotionAnalysis(context.Context, *GetEmotionAnalysisRequest) (*AdminEmotionAnalysis, error)
	GetFile(context.Context, *GetFileRequest) (*AdminFile, error)
	GetUser(context.Context, *GetUserRequest) (*AdminUser, error)
	ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error)
	ListChatMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesResponse, error)
	ListChatSessions(context.Context, *ListChatSessionsRequest) (*ListChatSessionsResponse, error)
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	ListDiaries(context.Context, *ListDiariesRequest) (*ListDiariesResponse, error)
	ListEmotionAnalyses(context.Context, *ListEmotionAnalysesRequest) (*ListEmotionAnalysesResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ListLoginLogs(context.Context, *ListLoginLogsRequest) (*ListLoginLogsResponse, error)
	ListMoodTags(context.Context, *ListMoodTagsRequest) (*ListMoodTagsResponse, error)
	ListSecurityEvents(context.Context, *ListSecurityEventsRequest) (*ListSecurityEventsResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error)
	UpdateAnnouncement(context.Context, *UpdateAnnouncementRequest) (*AdminAnnouncement, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*AdminSystemConfig, error)
	UpdateMoodTag(context.Context, *UpdateMoodTagRequest) (*AdminMoodTag, error)
	UpdateUserPassword(context.Context, *UpdateUserPasswordRequest) (*emptypb.Empty, error)
	UpdateUserRoles(context.Context, *UpdateUserRolesRequest) (*AdminUser, error)
	UpdateUserStatus(context.Context, *UpdateUserStatusRequest) (*AdminUser, error)
	UpdateVersion(context.Context, *UpdateVersionRequest) (*AdminAppVersion, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/admin/dashboard/overview", _AdminService_GetDashboardOverview0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/dashboard/trends", _AdminService_GetDashboardTrends0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/users", _AdminService_ListUsers0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/users/{user_id}", _AdminService_GetUser0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/users/{user_id}/status", _AdminService_UpdateUserStatus0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/users/{user_id}/roles", _AdminService_UpdateUserRoles0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/users/{user_id}/password", _AdminService_UpdateUserPassword0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/diaries", _AdminService_ListDiaries0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/diaries/{id}", _AdminService_GetDiary0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/diaries/{id}", _AdminService_DeleteDiary0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/emotion/analyses", _AdminService_ListEmotionAnalyses0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/emotion/analyses/{id}", _AdminService_GetEmotionAnalysis0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/chat/sessions", _AdminService_ListChatSessions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/chat/sessions/{session_id}/messages", _AdminService_ListChatMessages0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/security/login-logs", _AdminService_ListLoginLogs0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/security/events", _AdminService_ListSecurityEvents0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/system/configs", _AdminService_ListConfigs0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/system/configs", _AdminService_CreateConfig0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/system/configs/{id}", _AdminService_UpdateConfig0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/system/configs/{id}", _AdminService_DeleteConfig0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/system/announcements", _AdminService_ListAnnouncements0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/system/announcements", _AdminService_CreateAnnouncement0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/system/announcements/{id}", _AdminService_UpdateAnnouncement0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/system/announcements/{id}", _AdminService_DeleteAnnouncement0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/system/versions", _AdminService_ListVersions0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/system/versions", _AdminService_CreateVersion0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/system/versions/{id}", _AdminService_UpdateVersion0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/system/versions/{id}", _AdminService_DeleteVersion0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/mood-tags", _AdminService_ListMoodTags0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/mood-tags", _AdminService_CreateMoodTag0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/mood-tags/{id}", _AdminService_UpdateMoodTag0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/mood-tags/{id}", _AdminService_DeleteMoodTag0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/files", _AdminService_ListFiles0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/files/{id}", _AdminService_GetFile0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/files/{id}", _AdminService_DeleteFile0_HTTP_Handler(srv))
}

func _AdminService_GetDashboardOverview0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDashboardOverviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetDashboardOverview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDashboardOverview(ctx, req.(*GetDashboardOverviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DashboardOverview)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetDashboardTrends0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDashboardTrendsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetDashboardTrends)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDashboardTrends(ctx, req.(*GetDashboardTrendsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DashboardTrends)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListUsers0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetUser0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminUser)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateUserStatus0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateUserStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserStatus(ctx, req.(*UpdateUserStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminUser)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateUserRoles0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserRolesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateUserRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserRoles(ctx, req.(*UpdateUserRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminUser)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateUserPassword0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateUserPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserPassword(ctx, req.(*UpdateUserPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListDiaries0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDiariesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListDiaries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDiaries(ctx, req.(*ListDiariesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDiariesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetDiary0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDiaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDiary(ctx, req.(*GetDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminDiary)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteDiary0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDiaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDiary(ctx, req.(*DeleteDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListEmotionAnalyses0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEmotionAnalysesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListEmotionAnalyses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEmotionAnalyses(ctx, req.(*ListEmotionAnalysesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEmotionAnalysesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetEmotionAnalysis0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmotionAnalysisRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetEmotionAnalysis)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmotionAnalysis(ctx, req.(*GetEmotionAnalysisRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminEmotionAnalysis)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListChatSessions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListChatSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListChatSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChatSessions(ctx, req.(*ListChatSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListChatSessionsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListChatMessages0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListChatMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListChatMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChatMessages(ctx, req.(*ListChatMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListChatMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListLoginLogs0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLoginLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListLoginLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLoginLogs(ctx, req.(*ListLoginLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLoginLogsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListSecurityEvents0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSecurityEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListSecurityEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSecurityEvents(ctx, req.(*ListSecurityEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSecurityEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListConfigs0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConfigsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListConfigs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConfigs(ctx, req.(*ListConfigsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListConfigsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConfig(ctx, req.(*CreateConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminSystemConfig)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConfig(ctx, req.(*UpdateConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminSystemConfig)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteConfig0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteConfig(ctx, req.(*DeleteConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListAnnouncements0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAnnouncementsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListAnnouncements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAnnouncements(ctx, req.(*ListAnnouncementsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAnnouncementsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateAnnouncement0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAnnouncementRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateAnnouncement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAnnouncement(ctx, req.(*CreateAnnouncementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminAnnouncement)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateAnnouncement0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAnnouncementRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateAnnouncement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAnnouncement(ctx, req.(*UpdateAnnouncementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminAnnouncement)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteAnnouncement0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAnnouncementRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteAnnouncement)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAnnouncement(ctx, req.(*DeleteAnnouncementRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListVersions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVersionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListVersions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVersions(ctx, req.(*ListVersionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVersionsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateVersion0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateVersion(ctx, req.(*CreateVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminAppVersion)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateVersion0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateVersion(ctx, req.(*UpdateVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminAppVersion)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteVersion0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteVersion(ctx, req.(*DeleteVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListMoodTags0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMoodTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListMoodTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMoodTags(ctx, req.(*ListMoodTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMoodTagsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateMoodTag0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMoodTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateMoodTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMoodTag(ctx, req.(*CreateMoodTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminMoodTag)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateMoodTag0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMoodTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateMoodTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMoodTag(ctx, req.(*UpdateMoodTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminMoodTag)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteMoodTag0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMoodTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteMoodTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMoodTag(ctx, req.(*DeleteMoodTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListFiles0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFiles(ctx, req.(*ListFilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFilesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetFile0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFile(ctx, req.(*GetFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminFile)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteFile0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteFile(ctx, req.(*DeleteFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	CreateAnnouncement(ctx context.Context, req *CreateAnnouncementRequest, opts ...http.CallOption) (rsp *AdminAnnouncement, err error)
	CreateConfig(ctx context.Context, req *CreateConfigRequest, opts ...http.CallOption) (rsp *AdminSystemConfig, err error)
	CreateMoodTag(ctx context.Context, req *CreateMoodTagRequest, opts ...http.CallOption) (rsp *AdminMoodTag, err error)
	CreateVersion(ctx context.Context, req *CreateVersionRequest, opts ...http.CallOption) (rsp *AdminAppVersion, err error)
	DeleteAnnouncement(ctx context.Context, req *DeleteAnnouncementRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteConfig(ctx context.Context, req *DeleteConfigRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteDiary(ctx context.Context, req *DeleteDiaryRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteFile(ctx context.Context, req *DeleteFileRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteMoodTag(ctx context.Context, req *DeleteMoodTagRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteVersion(ctx context.Context, req *DeleteVersionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetDashboardOverview(ctx context.Context, req *GetDashboardOverviewRequest, opts ...http.CallOption) (rsp *DashboardOverview, err error)
	GetDashboardTrends(ctx context.Context, req *GetDashboardTrendsRequest, opts ...http.CallOption) (rsp *DashboardTrends, err error)
	GetDiary(ctx context.Context, req *GetDiaryRequest, opts ...http.CallOption) (rsp *AdminDiary, err error)
	GetEmotionAnalysis(ctx context.Context, req *GetEmotionAnalysisRequest, opts ...http.CallOption) (rsp *AdminEmotionAnalysis, err error)
	GetFile(ctx context.Context, req *GetFileRequest, opts ...http.CallOption) (rsp *AdminFile, err error)
	GetUser(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *AdminUser, err error)
	ListAnnouncements(ctx context.Context, req *ListAnnouncementsRequest, opts ...http.CallOption) (rsp *ListAnnouncementsResponse, err error)
	ListChatMessages(ctx context.Context, req *ListChatMessagesRequest, opts ...http.CallOption) (rsp *ListChatMessagesResponse, err error)
	ListChatSessions(ctx context.Context, req *ListChatSessionsRequest, opts ...http.CallOption) (rsp *ListChatSessionsResponse, err error)
	ListConfigs(ctx context.Context, req *ListConfigsRequest, opts ...http.CallOption) (rsp *ListConfigsResponse, err error)
	ListDiaries(ctx context.Context, req *ListDiariesRequest, opts ...http.CallOption) (rsp *ListDiariesResponse, err error)
	ListEmotionAnalyses(ctx context.Context, req *ListEmotionAnalysesRequest, opts ...http.CallOption) (rsp *ListEmotionAnalysesResponse, err error)
	ListFiles(ctx context.Context, req *ListFilesRequest, opts ...http.CallOption) (rsp *ListFilesResponse, err error)
	ListLoginLogs(ctx context.Context, req *ListLoginLogsRequest, opts ...http.CallOption) (rsp *ListLoginLogsResponse, err error)
	ListMoodTags(ctx context.Context, req *ListMoodTagsRequest, opts ...http.CallOption) (rsp *ListMoodTagsResponse, err error)
	ListSecurityEvents(ctx context.Context, req *ListSecurityEventsRequest, opts ...http.CallOption) (rsp *ListSecurityEventsResponse, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...http.CallOption) (rsp *ListUsersResponse, err error)
	ListVersions(ctx context.Context, req *ListVersionsRequest, opts ...http.CallOption) (rsp *ListVersionsResponse, err error)
	UpdateAnnouncement(ctx context.Context, req *UpdateAnnouncementRequest, opts ...http.CallOption) (rsp *AdminAnnouncement, err error)
	UpdateConfig(ctx context.Context, req *UpdateConfigRequest, opts ...http.CallOption) (rsp *AdminSystemConfig, err error)
	UpdateMoodTag(ctx context.Context, req *UpdateMoodTagRequest, opts ...http.CallOption) (rsp *AdminMoodTag, err error)
	UpdateUserPassword(ctx context.Context, req *UpdateUserPasswordRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateUserRoles(ctx context.Context, req *UpdateUserRolesRequest, opts ...http.CallOption) (rsp *AdminUser, err error)
	UpdateUserStatus(ctx context.Context, req *UpdateUserStatusRequest, opts ...http.CallOption) (rsp *AdminUser, err error)
	UpdateVersion(ctx context.Context, req *UpdateVersionRequest, opts ...http.CallOption) (rsp *AdminAppVersion, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

func (c *AdminServiceHTTPClientImpl) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...http.CallOption) (*AdminAnnouncement, error) {
	var out AdminAnnouncement
	pattern := "/v1/admin/system/announcements"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateAnnouncement),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...http.CallOption) (*AdminSystemConfig, error) {
	var out AdminSystemConfig
	pattern := "/v1/admin/system/configs"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateMoodTag(ctx context.Context, in *CreateMoodTagRequest, opts ...http.CallOption) (*AdminMoodTag, error) {
	var out AdminMoodTag
	pattern := "/v1/admin/mood-tags"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateMoodTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...http.CallOption) (*AdminAppVersion, error) {
	var out AdminAppVersion
	pattern := "/v1/admin/system/versions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/system/announcements/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteAnnouncement),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/system/configs/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteDiary(ctx context.Context, in *DeleteDiaryRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/diaries/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/files/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteMoodTag(ctx context.Context, in *DeleteMoodTagRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/mood-tags/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteMoodTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteVersion(ctx context.Context, in *DeleteVersionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/system/versions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetDashboardOverview(ctx context.Context, in *GetDashboardOverviewRequest, opts ...http.CallOption) (*DashboardOverview, error) {
	var out DashboardOverview
	pattern := "/v1/admin/dashboard/overview"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetDashboardOverview),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetDashboardTrends(ctx context.Context, in *GetDashboardTrendsRequest, opts ...http.CallOption) (*DashboardTrends, error) {
	var out DashboardTrends
	pattern := "/v1/admin/dashboard/trends"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetDashboardTrends),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetDiary(ctx context.Context, in *GetDiaryRequest, opts ...http.CallOption) (*AdminDiary, error) {
	var out AdminDiary
	pattern := "/v1/admin/diaries/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetEmotionAnalysis(ctx context.Context, in *GetEmotionAnalysisRequest, opts ...http.CallOption) (*AdminEmotionAnalysis, error) {
	var out AdminEmotionAnalysis
	pattern := "/v1/admin/emotion/analyses/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetEmotionAnalysis),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetFile(ctx context.Context, in *GetFileRequest, opts ...http.CallOption) (*AdminFile, error) {
	var out AdminFile
	pattern := "/v1/admin/files/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*AdminUser, error) {
	var out AdminUser
	pattern := "/v1/admin/users/{user_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...http.CallOption) (*ListAnnouncementsResponse, error) {
	var out ListAnnouncementsResponse
	pattern := "/v1/admin/system/announcements"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListAnnouncements),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListChatMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...http.CallOption) (*ListChatMessagesResponse, error) {
	var out ListChatMessagesResponse
	pattern := "/v1/admin/chat/sessions/{session_id}/messages"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListChatMessages),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListChatSessions(ctx context.Context, in *ListChatSessionsRequest, opts ...http.CallOption) (*ListChatSessionsResponse, error) {
	var out ListChatSessionsResponse
	pattern := "/v1/admin/chat/sessions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListChatSessions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...http.CallOption) (*ListConfigsResponse, error) {
	var out ListConfigsResponse
	pattern := "/v1/admin/system/configs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListConfigs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListDiaries(ctx context.Context, in *ListDiariesRequest, opts ...http.CallOption) (*ListDiariesResponse, error) {
	var out ListDiariesResponse
	pattern := "/v1/admin/diaries"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListDiaries),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListEmotionAnalyses(ctx context.Context, in *ListEmotionAnalysesRequest, opts ...http.CallOption) (*ListEmotionAnalysesResponse, error) {
	var out ListEmotionAnalysesResponse
	pattern := "/v1/admin/emotion/analyses"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListEmotionAnalyses),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...http.CallOption) (*ListFilesResponse, error) {
	var out ListFilesResponse
	pattern := "/v1/admin/files"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListFiles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListLoginLogs(ctx context.Context, in *ListLoginLogsRequest, opts ...http.CallOption) (*ListLoginLogsResponse, error) {
	var out ListLoginLogsResponse
	pattern := "/v1/admin/security/login-logs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListLoginLogs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListMoodTags(ctx context.Context, in *ListMoodTagsRequest, opts ...http.CallOption) (*ListMoodTagsResponse, error) {
	var out ListMoodTagsResponse
	pattern := "/v1/admin/mood-tags"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListMoodTags),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListSecurityEvents(ctx context.Context, in *ListSecurityEventsRequest, opts ...http.CallOption) (*ListSecurityEventsResponse, error) {
	var out ListSecurityEventsResponse
	pattern := "/v1/admin/security/events"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListSecurityEvents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...http.CallOption) (*ListUsersResponse, error) {
	var out ListUsersResponse
	pattern := "/v1/admin/users"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListUsers),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...http.CallOption) (*ListVersionsResponse, error) {
	var out ListVersionsResponse
	pattern := "/v1/admin/system/versions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListVersions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateAnnouncement(ctx context.Context, in *UpdateAnnouncementRequest, opts ...http.CallOption) (*AdminAnnouncement, error) {
	var out AdminAnnouncement
	pattern := "/v1/admin/system/announcements/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateAnnouncement),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...http.CallOption) (*AdminSystemConfig, error) {
	var out AdminSystemConfig
	pattern := "/v1/admin/system/configs/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateConfig),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateMoodTag(ctx context.Context, in *UpdateMoodTagRequest, opts ...http.CallOption) (*AdminMoodTag, error) {
	var out AdminMoodTag
	pattern := "/v1/admin/mood-tags/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateMoodTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/users/{user_id}/password"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateUserPassword),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateUserRoles(ctx context.Context, in *UpdateUserRolesRequest, opts ...http.CallOption) (*AdminUser, error) {
	var out AdminUser
	pattern := "/v1/admin/users/{user_id}/roles"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateUserRoles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...http.CallOption) (*AdminUser, error) {
	var out AdminUser
	pattern := "/v1/admin/users/{user_id}/status"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateUserStatus),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateVersion(ctx context.Context, in *UpdateVersionRequest, opts ...http.CallOption) (*AdminAppVersion, error) {
	var out AdminAppVersion
	pattern := "/v1/admin/system/versions/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
