// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: aichat/v1/aichat.proto

package aichatv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAIChatServiceChat = "/aichat.v1.AIChatService/Chat"
const OperationAIChatServiceCreateConversation = "/aichat.v1.AIChatService/CreateConversation"
const OperationAIChatServiceCreateKnowledgeDocument = "/aichat.v1.AIChatService/CreateKnowledgeDocument"
const OperationAIChatServiceHealth = "/aichat.v1.AIChatService/Health"
const OperationAIChatServiceListConversations = "/aichat.v1.AIChatService/ListConversations"
const OperationAIChatServiceListKnowledgeDocuments = "/aichat.v1.AIChatService/ListKnowledgeDocuments"
const OperationAIChatServiceListMessages = "/aichat.v1.AIChatService/ListMessages"

type AIChatServiceHTTPServer interface {
	// Chat Chat sends a non-streaming chat request and waits for the full AI answer.
	Chat(context.Context, *ChatRequest) (*ChatReply, error)
	// CreateConversation CreateConversation creates a new conversation for the authenticated user.
	CreateConversation(context.Context, *CreateConversationRequest) (*Conversation, error)
	// CreateKnowledgeDocument CreateKnowledgeDocument uploads text knowledge into the user's knowledge base.
	CreateKnowledgeDocument(context.Context, *CreateKnowledgeDocumentRequest) (*KnowledgeDocument, error)
	// Health Health proxies the downstream FastAPI health endpoint.
	Health(context.Context, *HealthRequest) (*HealthReply, error)
	// ListConversations ListConversations returns conversations owned by the authenticated user.
	ListConversations(context.Context, *ListConversationsRequest) (*ConversationSet, error)
	// ListKnowledgeDocuments ListKnowledgeDocuments returns the user's knowledge base documents.
	ListKnowledgeDocuments(context.Context, *ListKnowledgeDocumentsRequest) (*KnowledgeDocumentSet, error)
	// ListMessages ListMessages returns messages in one conversation owned by the user.
	ListMessages(context.Context, *ListMessagesRequest) (*MessageSet, error)
}

func RegisterAIChatServiceHTTPServer(s *http.Server, srv AIChatServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/health", _AIChatService_Health0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/conversations", _AIChatService_CreateConversation0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/conversations", _AIChatService_ListConversations0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/conversations/{conversation_id}/messages", _AIChatService_ListMessages0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/chat", _AIChatService_Chat0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/knowledge/documents", _AIChatService_CreateKnowledgeDocument0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/knowledge/documents", _AIChatService_ListKnowledgeDocuments0_HTTP_Handler(srv))
}

func _AIChatService_Health0_HTTP_Handler(srv AIChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIChatServiceHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*HealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthReply)
		return ctx.Result(200, reply)
	}
}

func _AIChatService_CreateConversation0_HTTP_Handler(srv AIChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateConversationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIChatServiceCreateConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConversation(ctx, req.(*CreateConversationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Conversation)
		return ctx.Result(200, reply)
	}
}

func _AIChatService_ListConversations0_HTTP_Handler(srv AIChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConversationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIChatServiceListConversations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConversations(ctx, req.(*ListConversationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConversationSet)
		return ctx.Result(200, reply)
	}
}

func _AIChatService_ListMessages0_HTTP_Handler(srv AIChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIChatServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MessageSet)
		return ctx.Result(200, reply)
	}
}

func _AIChatService_Chat0_HTTP_Handler(srv AIChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIChatServiceChat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Chat(ctx, req.(*ChatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatReply)
		return ctx.Result(200, reply)
	}
}

func _AIChatService_CreateKnowledgeDocument0_HTTP_Handler(srv AIChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateKnowledgeDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIChatServiceCreateKnowledgeDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateKnowledgeDocument(ctx, req.(*CreateKnowledgeDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeDocument)
		return ctx.Result(200, reply)
	}
}

func _AIChatService_ListKnowledgeDocuments0_HTTP_Handler(srv AIChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListKnowledgeDocumentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIChatServiceListKnowledgeDocuments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKnowledgeDocuments(ctx, req.(*ListKnowledgeDocumentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*KnowledgeDocumentSet)
		return ctx.Result(200, reply)
	}
}

type AIChatServiceHTTPClient interface {
	// Chat Chat sends a non-streaming chat request and waits for the full AI answer.
	Chat(ctx context.Context, req *ChatRequest, opts ...http.CallOption) (rsp *ChatReply, err error)
	// CreateConversation CreateConversation creates a new conversation for the authenticated user.
	CreateConversation(ctx context.Context, req *CreateConversationRequest, opts ...http.CallOption) (rsp *Conversation, err error)
	// CreateKnowledgeDocument CreateKnowledgeDocument uploads text knowledge into the user's knowledge base.
	CreateKnowledgeDocument(ctx context.Context, req *CreateKnowledgeDocumentRequest, opts ...http.CallOption) (rsp *KnowledgeDocument, err error)
	// Health Health proxies the downstream FastAPI health endpoint.
	Health(ctx context.Context, req *HealthRequest, opts ...http.CallOption) (rsp *HealthReply, err error)
	// ListConversations ListConversations returns conversations owned by the authenticated user.
	ListConversations(ctx context.Context, req *ListConversationsRequest, opts ...http.CallOption) (rsp *ConversationSet, err error)
	// ListKnowledgeDocuments ListKnowledgeDocuments returns the user's knowledge base documents.
	ListKnowledgeDocuments(ctx context.Context, req *ListKnowledgeDocumentsRequest, opts ...http.CallOption) (rsp *KnowledgeDocumentSet, err error)
	// ListMessages ListMessages returns messages in one conversation owned by the user.
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *MessageSet, err error)
}

type AIChatServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAIChatServiceHTTPClient(client *http.Client) AIChatServiceHTTPClient {
	return &AIChatServiceHTTPClientImpl{client}
}

// Chat Chat sends a non-streaming chat request and waits for the full AI answer.
func (c *AIChatServiceHTTPClientImpl) Chat(ctx context.Context, in *ChatRequest, opts ...http.CallOption) (*ChatReply, error) {
	var out ChatReply
	pattern := "/api/v1/chat"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAIChatServiceChat),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateConversation CreateConversation creates a new conversation for the authenticated user.
func (c *AIChatServiceHTTPClientImpl) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...http.CallOption) (*Conversation, error) {
	var out Conversation
	pattern := "/api/v1/conversations"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAIChatServiceCreateConversation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateKnowledgeDocument CreateKnowledgeDocument uploads text knowledge into the user's knowledge base.
func (c *AIChatServiceHTTPClientImpl) CreateKnowledgeDocument(ctx context.Context, in *CreateKnowledgeDocumentRequest, opts ...http.CallOption) (*KnowledgeDocument, error) {
	var out KnowledgeDocument
	pattern := "/api/v1/knowledge/documents"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAIChatServiceCreateKnowledgeDocument),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Health Health proxies the downstream FastAPI health endpoint.
func (c *AIChatServiceHTTPClientImpl) Health(ctx context.Context, in *HealthRequest, opts ...http.CallOption) (*HealthReply, error) {
	var out HealthReply
	pattern := "/api/v1/health"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAIChatServiceHealth),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListConversations ListConversations returns conversations owned by the authenticated user.
func (c *AIChatServiceHTTPClientImpl) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...http.CallOption) (*ConversationSet, error) {
	var out ConversationSet
	pattern := "/api/v1/conversations"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAIChatServiceListConversations),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListKnowledgeDocuments ListKnowledgeDocuments returns the user's knowledge base documents.
func (c *AIChatServiceHTTPClientImpl) ListKnowledgeDocuments(ctx context.Context, in *ListKnowledgeDocumentsRequest, opts ...http.CallOption) (*KnowledgeDocumentSet, error) {
	var out KnowledgeDocumentSet
	pattern := "/api/v1/knowledge/documents"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAIChatServiceListKnowledgeDocuments),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMessages ListMessages returns messages in one conversation owned by the user.
func (c *AIChatServiceHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*MessageSet, error) {
	var out MessageSet
	pattern := "/api/v1/conversations/{conversation_id}/messages"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAIChatServiceListMessages),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
