// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: file/v1/file.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationFileServiceCreateFile = "/file.v1.FileService/CreateFile"
const OperationFileServiceCreateUploadToken = "/file.v1.FileService/CreateUploadToken"
const OperationFileServiceDeleteFile = "/file.v1.FileService/DeleteFile"
const OperationFileServiceGetFile = "/file.v1.FileService/GetFile"

type FileServiceHTTPServer interface {
	// CreateFile 登记文件元数据，用于头像、日记附件等业务资源。
	CreateFile(context.Context, *CreateFileRequest) (*FileAsset, error)
	// CreateUploadToken 创建上传凭证，返回上传地址、对象 key 和公开访问地址。
	CreateUploadToken(context.Context, *CreateUploadTokenRequest) (*UploadToken, error)
	// DeleteFile 删除当前用户指定文件资源记录。
	DeleteFile(context.Context, *DeleteFileRequest) (*emptypb.Empty, error)
	// GetFile 查询当前用户指定文件元数据。
	GetFile(context.Context, *GetFileRequest) (*FileAsset, error)
}

func RegisterFileServiceHTTPServer(s *http.Server, srv FileServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/files/upload-token", _FileService_CreateUploadToken0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/files", _FileService_CreateFile0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/files/{id}", _FileService_GetFile0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/files/{id}", _FileService_DeleteFile0_HTTP_Handler(srv))
}

func _FileService_CreateUploadToken0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateUploadTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceCreateUploadToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUploadToken(ctx, req.(*CreateUploadTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadToken)
		return ctx.Result(200, reply)
	}
}

func _FileService_CreateFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceCreateFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFile(ctx, req.(*CreateFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FileAsset)
		return ctx.Result(200, reply)
	}
}

func _FileService_GetFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceGetFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFile(ctx, req.(*GetFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FileAsset)
		return ctx.Result(200, reply)
	}
}

func _FileService_DeleteFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceDeleteFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteFile(ctx, req.(*DeleteFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type FileServiceHTTPClient interface {
	// CreateFile 登记文件元数据，用于头像、日记附件等业务资源。
	CreateFile(ctx context.Context, req *CreateFileRequest, opts ...http.CallOption) (rsp *FileAsset, err error)
	// CreateUploadToken 创建上传凭证，返回上传地址、对象 key 和公开访问地址。
	CreateUploadToken(ctx context.Context, req *CreateUploadTokenRequest, opts ...http.CallOption) (rsp *UploadToken, err error)
	// DeleteFile 删除当前用户指定文件资源记录。
	DeleteFile(ctx context.Context, req *DeleteFileRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetFile 查询当前用户指定文件元数据。
	GetFile(ctx context.Context, req *GetFileRequest, opts ...http.CallOption) (rsp *FileAsset, err error)
}

type FileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewFileServiceHTTPClient(client *http.Client) FileServiceHTTPClient {
	return &FileServiceHTTPClientImpl{client}
}

// CreateFile 登记文件元数据，用于头像、日记附件等业务资源。
func (c *FileServiceHTTPClientImpl) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...http.CallOption) (*FileAsset, error) {
	var out FileAsset
	pattern := "/v1/files"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceCreateFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateUploadToken 创建上传凭证，返回上传地址、对象 key 和公开访问地址。
func (c *FileServiceHTTPClientImpl) CreateUploadToken(ctx context.Context, in *CreateUploadTokenRequest, opts ...http.CallOption) (*UploadToken, error) {
	var out UploadToken
	pattern := "/v1/files/upload-token"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationFileServiceCreateUploadToken),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteFile 删除当前用户指定文件资源记录。
func (c *FileServiceHTTPClientImpl) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/files/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceDeleteFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFile 查询当前用户指定文件元数据。
func (c *FileServiceHTTPClientImpl) GetFile(ctx context.Context, in *GetFileRequest, opts ...http.CallOption) (*FileAsset, error) {
	var out FileAsset
	pattern := "/v1/files/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationFileServiceGetFile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
