server:
  http:
    network: tcp
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
    timeout: 30s
data:
  database:
    driver: mysql
    source: root:root123456@tcp(127.0.0.1:3306)/emo_ai?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    network: tcp
    addr: 127.0.0.1:6379
    read_timeout: 3s
    write_timeout: 3s
