// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: diary/v1/diary.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiaryService_CreateDiary_FullMethodName = "/diary.v1.DiaryService/CreateDiary"
	DiaryService_ListDiaries_FullMethodName = "/diary.v1.DiaryService/ListDiaries"
	DiaryService_GetDiary_FullMethodName    = "/diary.v1.DiaryService/GetDiary"
	DiaryService_UpdateDiary_FullMethodName = "/diary.v1.DiaryService/UpdateDiary"
	DiaryService_DeleteDiary_FullMethodName = "/diary.v1.DiaryService/DeleteDiary"
	DiaryService_ListTags_FullMethodName    = "/diary.v1.DiaryService/ListTags"
	DiaryService_CreateTag_FullMethodName   = "/diary.v1.DiaryService/CreateTag"
	DiaryService_UpdateTag_FullMethodName   = "/diary.v1.DiaryService/UpdateTag"
	DiaryService_DeleteTag_FullMethodName   = "/diary.v1.DiaryService/DeleteTag"
)

// DiaryServiceClient is the client API for DiaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiaryServiceClient interface {
	// 新增心情日记，保存正文、心情分数、标签和附件。
	CreateDiary(ctx context.Context, in *CreateDiaryRequest, opts ...grpc.CallOption) (*MoodDiary, error)
	// 分页查询当前用户的心情日记，支持标签、心情、日期范围筛选。
	ListDiaries(ctx context.Context, in *ListDiariesRequest, opts ...grpc.CallOption) (*ListDiariesResponse, error)
	// 获取当前用户指定心情日记详情。
	GetDiary(ctx context.Context, in *GetDiaryRequest, opts ...grpc.CallOption) (*MoodDiary, error)
	// 修改当前用户指定心情日记内容、情绪信息、标签和附件。
	UpdateDiary(ctx context.Context, in *UpdateDiaryRequest, opts ...grpc.CallOption) (*MoodDiary, error)
	// 删除当前用户指定心情日记。
	DeleteDiary(ctx context.Context, in *DeleteDiaryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 查询系统标签和当前用户自定义心情标签。
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	// 创建当前用户自定义心情标签。
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*MoodTag, error)
	// 修改当前用户自定义心情标签。
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*MoodTag, error)
	// 删除当前用户自定义心情标签。
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type diaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiaryServiceClient(cc grpc.ClientConnInterface) DiaryServiceClient {
	return &diaryServiceClient{cc}
}

func (c *diaryServiceClient) CreateDiary(ctx context.Context, in *CreateDiaryRequest, opts ...grpc.CallOption) (*MoodDiary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoodDiary)
	err := c.cc.Invoke(ctx, DiaryService_CreateDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) ListDiaries(ctx context.Context, in *ListDiariesRequest, opts ...grpc.CallOption) (*ListDiariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiariesResponse)
	err := c.cc.Invoke(ctx, DiaryService_ListDiaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiary(ctx context.Context, in *GetDiaryRequest, opts ...grpc.CallOption) (*MoodDiary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoodDiary)
	err := c.cc.Invoke(ctx, DiaryService_GetDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) UpdateDiary(ctx context.Context, in *UpdateDiaryRequest, opts ...grpc.CallOption) (*MoodDiary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoodDiary)
	err := c.cc.Invoke(ctx, DiaryService_UpdateDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) DeleteDiary(ctx context.Context, in *DeleteDiaryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DiaryService_DeleteDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, DiaryService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*MoodTag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoodTag)
	err := c.cc.Invoke(ctx, DiaryService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*MoodTag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoodTag)
	err := c.cc.Invoke(ctx, DiaryService_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DiaryService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiaryServiceServer is the server API for DiaryService service.
// All implementations must embed UnimplementedDiaryServiceServer
// for forward compatibility.
type DiaryServiceServer interface {
	// 新增心情日记，保存正文、心情分数、标签和附件。
	CreateDiary(context.Context, *CreateDiaryRequest) (*MoodDiary, error)
	// 分页查询当前用户的心情日记，支持标签、心情、日期范围筛选。
	ListDiaries(context.Context, *ListDiariesRequest) (*ListDiariesResponse, error)
	// 获取当前用户指定心情日记详情。
	GetDiary(context.Context, *GetDiaryRequest) (*MoodDiary, error)
	// 修改当前用户指定心情日记内容、情绪信息、标签和附件。
	UpdateDiary(context.Context, *UpdateDiaryRequest) (*MoodDiary, error)
	// 删除当前用户指定心情日记。
	DeleteDiary(context.Context, *DeleteDiaryRequest) (*emptypb.Empty, error)
	// 查询系统标签和当前用户自定义心情标签。
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	// 创建当前用户自定义心情标签。
	CreateTag(context.Context, *CreateTagRequest) (*MoodTag, error)
	// 修改当前用户自定义心情标签。
	UpdateTag(context.Context, *UpdateTagRequest) (*MoodTag, error)
	// 删除当前用户自定义心情标签。
	DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDiaryServiceServer()
}

// UnimplementedDiaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiaryServiceServer struct{}

func (UnimplementedDiaryServiceServer) CreateDiary(context.Context, *CreateDiaryRequest) (*MoodDiary, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDiary not implemented")
}
func (UnimplementedDiaryServiceServer) ListDiaries(context.Context, *ListDiariesRequest) (*ListDiariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiaries not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiary(context.Context, *GetDiaryRequest) (*MoodDiary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiary not implemented")
}
func (UnimplementedDiaryServiceServer) UpdateDiary(context.Context, *UpdateDiaryRequest) (*MoodDiary, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDiary not implemented")
}
func (UnimplementedDiaryServiceServer) DeleteDiary(context.Context, *DeleteDiaryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDiary not implemented")
}
func (UnimplementedDiaryServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedDiaryServiceServer) CreateTag(context.Context, *CreateTagRequest) (*MoodTag, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedDiaryServiceServer) UpdateTag(context.Context, *UpdateTagRequest) (*MoodTag, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedDiaryServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedDiaryServiceServer) mustEmbedUnimplementedDiaryServiceServer() {}
func (UnimplementedDiaryServiceServer) testEmbeddedByValue()                      {}

// UnsafeDiaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiaryServiceServer will
// result in compilation errors.
type UnsafeDiaryServiceServer interface {
	mustEmbedUnimplementedDiaryServiceServer()
}

func RegisterDiaryServiceServer(s grpc.ServiceRegistrar, srv DiaryServiceServer) {
	// If the following call panics, it indicates UnimplementedDiaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiaryService_ServiceDesc, srv)
}

func _DiaryService_CreateDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).CreateDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_CreateDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).CreateDiary(ctx, req.(*CreateDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_ListDiaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).ListDiaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_ListDiaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).ListDiaries(ctx, req.(*ListDiariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiary(ctx, req.(*GetDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_UpdateDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).UpdateDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_UpdateDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).UpdateDiary(ctx, req.(*UpdateDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_DeleteDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).DeleteDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_DeleteDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).DeleteDiary(ctx, req.(*DeleteDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiaryService_ServiceDesc is the grpc.ServiceDesc for DiaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diary.v1.DiaryService",
	HandlerType: (*DiaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDiary",
			Handler:    _DiaryService_CreateDiary_Handler,
		},
		{
			MethodName: "ListDiaries",
			Handler:    _DiaryService_ListDiaries_Handler,
		},
		{
			MethodName: "GetDiary",
			Handler:    _DiaryService_GetDiary_Handler,
		},
		{
			MethodName: "UpdateDiary",
			Handler:    _DiaryService_UpdateDiary_Handler,
		},
		{
			MethodName: "DeleteDiary",
			Handler:    _DiaryService_DeleteDiary_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _DiaryService_ListTags_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _DiaryService_CreateTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _DiaryService_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _DiaryService_DeleteTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diary/v1/diary.proto",
}
