// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: diary/v1/diary.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationDiaryServiceCreateDiary = "/diary.v1.DiaryService/CreateDiary"
const OperationDiaryServiceCreateTag = "/diary.v1.DiaryService/CreateTag"
const OperationDiaryServiceDeleteDiary = "/diary.v1.DiaryService/DeleteDiary"
const OperationDiaryServiceDeleteTag = "/diary.v1.DiaryService/DeleteTag"
const OperationDiaryServiceGetDiary = "/diary.v1.DiaryService/GetDiary"
const OperationDiaryServiceListDiaries = "/diary.v1.DiaryService/ListDiaries"
const OperationDiaryServiceListTags = "/diary.v1.DiaryService/ListTags"
const OperationDiaryServiceUpdateDiary = "/diary.v1.DiaryService/UpdateDiary"
const OperationDiaryServiceUpdateTag = "/diary.v1.DiaryService/UpdateTag"

type DiaryServiceHTTPServer interface {
	// CreateDiary 新增心情日记，保存正文、心情分数、标签和附件。
	CreateDiary(context.Context, *CreateDiaryRequest) (*MoodDiary, error)
	// CreateTag 创建当前用户自定义心情标签。
	CreateTag(context.Context, *CreateTagRequest) (*MoodTag, error)
	// DeleteDiary 删除当前用户指定心情日记。
	DeleteDiary(context.Context, *DeleteDiaryRequest) (*emptypb.Empty, error)
	// DeleteTag 删除当前用户自定义心情标签。
	DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error)
	// GetDiary 获取当前用户指定心情日记详情。
	GetDiary(context.Context, *GetDiaryRequest) (*MoodDiary, error)
	// ListDiaries 分页查询当前用户的心情日记，支持标签、心情、日期范围筛选。
	ListDiaries(context.Context, *ListDiariesRequest) (*ListDiariesResponse, error)
	// ListTags 查询系统标签和当前用户自定义心情标签。
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	// UpdateDiary 修改当前用户指定心情日记内容、情绪信息、标签和附件。
	UpdateDiary(context.Context, *UpdateDiaryRequest) (*MoodDiary, error)
	// UpdateTag 修改当前用户自定义心情标签。
	UpdateTag(context.Context, *UpdateTagRequest) (*MoodTag, error)
}

func RegisterDiaryServiceHTTPServer(s *http.Server, srv DiaryServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/diaries", _DiaryService_CreateDiary0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/diaries", _DiaryService_ListDiaries0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/diaries/{id}", _DiaryService_GetDiary0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/diaries/{id}", _DiaryService_UpdateDiary0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/diaries/{id}", _DiaryService_DeleteDiary0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/mood-tags", _DiaryService_ListTags0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/mood-tags", _DiaryService_CreateTag0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/mood-tags/{id}", _DiaryService_UpdateTag0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/mood-tags/{id}", _DiaryService_DeleteTag0_HTTP_Handler(srv))
}

func _DiaryService_CreateDiary0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDiaryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceCreateDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDiary(ctx, req.(*CreateDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoodDiary)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_ListDiaries0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDiariesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceListDiaries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDiaries(ctx, req.(*ListDiariesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDiariesResponse)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_GetDiary0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDiaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceGetDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDiary(ctx, req.(*GetDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoodDiary)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_UpdateDiary0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDiaryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceUpdateDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDiary(ctx, req.(*UpdateDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoodDiary)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_DeleteDiary0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDiaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceDeleteDiary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDiary(ctx, req.(*DeleteDiaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_ListTags0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceListTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTags(ctx, req.(*ListTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTagsResponse)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_CreateTag0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceCreateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTag(ctx, req.(*CreateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoodTag)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_UpdateTag0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceUpdateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTag(ctx, req.(*UpdateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoodTag)
		return ctx.Result(200, reply)
	}
}

func _DiaryService_DeleteTag0_HTTP_Handler(srv DiaryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDiaryServiceDeleteTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTag(ctx, req.(*DeleteTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type DiaryServiceHTTPClient interface {
	// CreateDiary 新增心情日记，保存正文、心情分数、标签和附件。
	CreateDiary(ctx context.Context, req *CreateDiaryRequest, opts ...http.CallOption) (rsp *MoodDiary, err error)
	// CreateTag 创建当前用户自定义心情标签。
	CreateTag(ctx context.Context, req *CreateTagRequest, opts ...http.CallOption) (rsp *MoodTag, err error)
	// DeleteDiary 删除当前用户指定心情日记。
	DeleteDiary(ctx context.Context, req *DeleteDiaryRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeleteTag 删除当前用户自定义心情标签。
	DeleteTag(ctx context.Context, req *DeleteTagRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetDiary 获取当前用户指定心情日记详情。
	GetDiary(ctx context.Context, req *GetDiaryRequest, opts ...http.CallOption) (rsp *MoodDiary, err error)
	// ListDiaries 分页查询当前用户的心情日记，支持标签、心情、日期范围筛选。
	ListDiaries(ctx context.Context, req *ListDiariesRequest, opts ...http.CallOption) (rsp *ListDiariesResponse, err error)
	// ListTags 查询系统标签和当前用户自定义心情标签。
	ListTags(ctx context.Context, req *ListTagsRequest, opts ...http.CallOption) (rsp *ListTagsResponse, err error)
	// UpdateDiary 修改当前用户指定心情日记内容、情绪信息、标签和附件。
	UpdateDiary(ctx context.Context, req *UpdateDiaryRequest, opts ...http.CallOption) (rsp *MoodDiary, err error)
	// UpdateTag 修改当前用户自定义心情标签。
	UpdateTag(ctx context.Context, req *UpdateTagRequest, opts ...http.CallOption) (rsp *MoodTag, err error)
}

type DiaryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDiaryServiceHTTPClient(client *http.Client) DiaryServiceHTTPClient {
	return &DiaryServiceHTTPClientImpl{client}
}

// CreateDiary 新增心情日记，保存正文、心情分数、标签和附件。
func (c *DiaryServiceHTTPClientImpl) CreateDiary(ctx context.Context, in *CreateDiaryRequest, opts ...http.CallOption) (*MoodDiary, error) {
	var out MoodDiary
	pattern := "/v1/diaries"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDiaryServiceCreateDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTag 创建当前用户自定义心情标签。
func (c *DiaryServiceHTTPClientImpl) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...http.CallOption) (*MoodTag, error) {
	var out MoodTag
	pattern := "/v1/mood-tags"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDiaryServiceCreateTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteDiary 删除当前用户指定心情日记。
func (c *DiaryServiceHTTPClientImpl) DeleteDiary(ctx context.Context, in *DeleteDiaryRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/diaries/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDiaryServiceDeleteDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTag 删除当前用户自定义心情标签。
func (c *DiaryServiceHTTPClientImpl) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/mood-tags/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDiaryServiceDeleteTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDiary 获取当前用户指定心情日记详情。
func (c *DiaryServiceHTTPClientImpl) GetDiary(ctx context.Context, in *GetDiaryRequest, opts ...http.CallOption) (*MoodDiary, error) {
	var out MoodDiary
	pattern := "/v1/diaries/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDiaryServiceGetDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListDiaries 分页查询当前用户的心情日记，支持标签、心情、日期范围筛选。
func (c *DiaryServiceHTTPClientImpl) ListDiaries(ctx context.Context, in *ListDiariesRequest, opts ...http.CallOption) (*ListDiariesResponse, error) {
	var out ListDiariesResponse
	pattern := "/v1/diaries"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDiaryServiceListDiaries),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTags 查询系统标签和当前用户自定义心情标签。
func (c *DiaryServiceHTTPClientImpl) ListTags(ctx context.Context, in *ListTagsRequest, opts ...http.CallOption) (*ListTagsResponse, error) {
	var out ListTagsResponse
	pattern := "/v1/mood-tags"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDiaryServiceListTags),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateDiary 修改当前用户指定心情日记内容、情绪信息、标签和附件。
func (c *DiaryServiceHTTPClientImpl) UpdateDiary(ctx context.Context, in *UpdateDiaryRequest, opts ...http.CallOption) (*MoodDiary, error) {
	var out MoodDiary
	pattern := "/v1/diaries/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDiaryServiceUpdateDiary),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTag 修改当前用户自定义心情标签。
func (c *DiaryServiceHTTPClientImpl) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...http.CallOption) (*MoodTag, error) {
	var out MoodTag
	pattern := "/v1/mood-tags/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDiaryServiceUpdateTag),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
