// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: profile/v1/profile.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileService_GetMe_FullMethodName                 = "/profile.v1.ProfileService/GetMe"
	ProfileService_UpdateProfile_FullMethodName         = "/profile.v1.ProfileService/UpdateProfile"
	ProfileService_UpdateAvatar_FullMethodName          = "/profile.v1.ProfileService/UpdateAvatar"
	ProfileService_GetPersonalProfile_FullMethodName    = "/profile.v1.ProfileService/GetPersonalProfile"
	ProfileService_SavePersonalProfile_FullMethodName   = "/profile.v1.ProfileService/SavePersonalProfile"
	ProfileService_ListTargetProfiles_FullMethodName    = "/profile.v1.ProfileService/ListTargetProfiles"
	ProfileService_SaveTargetProfile_FullMethodName     = "/profile.v1.ProfileService/SaveTargetProfile"
	ProfileService_ListImportantRecords_FullMethodName  = "/profile.v1.ProfileService/ListImportantRecords"
	ProfileService_SaveImportantRecord_FullMethodName   = "/profile.v1.ProfileService/SaveImportantRecord"
	ProfileService_DeleteImportantRecord_FullMethodName = "/profile.v1.ProfileService/DeleteImportantRecord"
)

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileServiceClient interface {
	// 获取当前登录用户的账号信息和个人资料，用于“我的页面”展示。
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserProfile, error)
	// 修改当前登录用户的个人资料，包括昵称、邮箱、生日、简介、地区等。
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	// 修改当前登录用户头像地址，并返回最新个人资料。
	UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...grpc.CallOption) (*UserProfile, error)
	GetPersonalProfile(ctx context.Context, in *GetPersonalProfileRequest, opts ...grpc.CallOption) (*PersonalProfile, error)
	SavePersonalProfile(ctx context.Context, in *SavePersonalProfileRequest, opts ...grpc.CallOption) (*PersonalProfile, error)
	ListTargetProfiles(ctx context.Context, in *ListTargetProfilesRequest, opts ...grpc.CallOption) (*ListTargetProfilesResponse, error)
	SaveTargetProfile(ctx context.Context, in *SaveTargetProfileRequest, opts ...grpc.CallOption) (*TargetProfile, error)
	ListImportantRecords(ctx context.Context, in *ListImportantRecordsRequest, opts ...grpc.CallOption) (*ListImportantRecordsResponse, error)
	SaveImportantRecord(ctx context.Context, in *SaveImportantRecordRequest, opts ...grpc.CallOption) (*ImportantRecord, error)
	DeleteImportantRecord(ctx context.Context, in *DeleteImportantRecordRequest, opts ...grpc.CallOption) (*DeleteImportantRecordResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, ProfileService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, ProfileService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, ProfileService_UpdateAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetPersonalProfile(ctx context.Context, in *GetPersonalProfileRequest, opts ...grpc.CallOption) (*PersonalProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonalProfile)
	err := c.cc.Invoke(ctx, ProfileService_GetPersonalProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) SavePersonalProfile(ctx context.Context, in *SavePersonalProfileRequest, opts ...grpc.CallOption) (*PersonalProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonalProfile)
	err := c.cc.Invoke(ctx, ProfileService_SavePersonalProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListTargetProfiles(ctx context.Context, in *ListTargetProfilesRequest, opts ...grpc.CallOption) (*ListTargetProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTargetProfilesResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListTargetProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) SaveTargetProfile(ctx context.Context, in *SaveTargetProfileRequest, opts ...grpc.CallOption) (*TargetProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetProfile)
	err := c.cc.Invoke(ctx, ProfileService_SaveTargetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListImportantRecords(ctx context.Context, in *ListImportantRecordsRequest, opts ...grpc.CallOption) (*ListImportantRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImportantRecordsResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListImportantRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) SaveImportantRecord(ctx context.Context, in *SaveImportantRecordRequest, opts ...grpc.CallOption) (*ImportantRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportantRecord)
	err := c.cc.Invoke(ctx, ProfileService_SaveImportantRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteImportantRecord(ctx context.Context, in *DeleteImportantRecordRequest, opts ...grpc.CallOption) (*DeleteImportantRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImportantRecordResponse)
	err := c.cc.Invoke(ctx, ProfileService_DeleteImportantRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility.
type ProfileServiceServer interface {
	// 获取当前登录用户的账号信息和个人资料，用于“我的页面”展示。
	GetMe(context.Context, *GetMeRequest) (*UserProfile, error)
	// 修改当前登录用户的个人资料，包括昵称、邮箱、生日、简介、地区等。
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UserProfile, error)
	// 修改当前登录用户头像地址，并返回最新个人资料。
	UpdateAvatar(context.Context, *UpdateAvatarRequest) (*UserProfile, error)
	GetPersonalProfile(context.Context, *GetPersonalProfileRequest) (*PersonalProfile, error)
	SavePersonalProfile(context.Context, *SavePersonalProfileRequest) (*PersonalProfile, error)
	ListTargetProfiles(context.Context, *ListTargetProfilesRequest) (*ListTargetProfilesResponse, error)
	SaveTargetProfile(context.Context, *SaveTargetProfileRequest) (*TargetProfile, error)
	ListImportantRecords(context.Context, *ListImportantRecordsRequest) (*ListImportantRecordsResponse, error)
	SaveImportantRecord(context.Context, *SaveImportantRecordRequest) (*ImportantRecord, error)
	DeleteImportantRecord(context.Context, *DeleteImportantRecordRequest) (*DeleteImportantRecordResponse, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileServiceServer struct{}

func (UnimplementedProfileServiceServer) GetMe(context.Context, *GetMeRequest) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedProfileServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedProfileServiceServer) UpdateAvatar(context.Context, *UpdateAvatarRequest) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAvatar not implemented")
}
func (UnimplementedProfileServiceServer) GetPersonalProfile(context.Context, *GetPersonalProfileRequest) (*PersonalProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersonalProfile not implemented")
}
func (UnimplementedProfileServiceServer) SavePersonalProfile(context.Context, *SavePersonalProfileRequest) (*PersonalProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePersonalProfile not implemented")
}
func (UnimplementedProfileServiceServer) ListTargetProfiles(context.Context, *ListTargetProfilesRequest) (*ListTargetProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTargetProfiles not implemented")
}
func (UnimplementedProfileServiceServer) SaveTargetProfile(context.Context, *SaveTargetProfileRequest) (*TargetProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveTargetProfile not implemented")
}
func (UnimplementedProfileServiceServer) ListImportantRecords(context.Context, *ListImportantRecordsRequest) (*ListImportantRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImportantRecords not implemented")
}
func (UnimplementedProfileServiceServer) SaveImportantRecord(context.Context, *SaveImportantRecordRequest) (*ImportantRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveImportantRecord not implemented")
}
func (UnimplementedProfileServiceServer) DeleteImportantRecord(context.Context, *DeleteImportantRecordRequest) (*DeleteImportantRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImportantRecord not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}
func (UnimplementedProfileServiceServer) testEmbeddedByValue()                        {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UpdateAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateAvatar(ctx, req.(*UpdateAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetPersonalProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonalProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetPersonalProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetPersonalProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetPersonalProfile(ctx, req.(*GetPersonalProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_SavePersonalProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePersonalProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).SavePersonalProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_SavePersonalProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).SavePersonalProfile(ctx, req.(*SavePersonalProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListTargetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTargetProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListTargetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListTargetProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListTargetProfiles(ctx, req.(*ListTargetProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_SaveTargetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTargetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).SaveTargetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_SaveTargetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).SaveTargetProfile(ctx, req.(*SaveTargetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListImportantRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImportantRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListImportantRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListImportantRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListImportantRecords(ctx, req.(*ListImportantRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_SaveImportantRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveImportantRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).SaveImportantRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_SaveImportantRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).SaveImportantRecord(ctx, req.(*SaveImportantRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteImportantRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImportantRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteImportantRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_DeleteImportantRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteImportantRecord(ctx, req.(*DeleteImportantRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.v1.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _ProfileService_GetMe_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _ProfileService_UpdateProfile_Handler,
		},
		{
			MethodName: "UpdateAvatar",
			Handler:    _ProfileService_UpdateAvatar_Handler,
		},
		{
			MethodName: "GetPersonalProfile",
			Handler:    _ProfileService_GetPersonalProfile_Handler,
		},
		{
			MethodName: "SavePersonalProfile",
			Handler:    _ProfileService_SavePersonalProfile_Handler,
		},
		{
			MethodName: "ListTargetProfiles",
			Handler:    _ProfileService_ListTargetProfiles_Handler,
		},
		{
			MethodName: "SaveTargetProfile",
			Handler:    _ProfileService_SaveTargetProfile_Handler,
		},
		{
			MethodName: "ListImportantRecords",
			Handler:    _ProfileService_ListImportantRecords_Handler,
		},
		{
			MethodName: "SaveImportantRecord",
			Handler:    _ProfileService_SaveImportantRecord_Handler,
		},
		{
			MethodName: "DeleteImportantRecord",
			Handler:    _ProfileService_DeleteImportantRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile/v1/profile.proto",
}
