// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: profile/v1/profile.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationProfileServiceGetMe = "/profile.v1.ProfileService/GetMe"
const OperationProfileServiceUpdateAvatar = "/profile.v1.ProfileService/UpdateAvatar"
const OperationProfileServiceUpdateProfile = "/profile.v1.ProfileService/UpdateProfile"

type ProfileServiceHTTPServer interface {
	// GetMe 获取当前登录用户的账号信息和个人资料，用于“我的页面”展示。
	GetMe(context.Context, *GetMeRequest) (*UserProfile, error)
	// UpdateAvatar 修改当前登录用户头像地址，并返回最新个人资料。
	UpdateAvatar(context.Context, *UpdateAvatarRequest) (*UserProfile, error)
	// UpdateProfile 修改当前登录用户的个人资料，包括昵称、邮箱、生日、简介、地区等。
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UserProfile, error)
}

func RegisterProfileServiceHTTPServer(s *http.Server, srv ProfileServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/users/me", _ProfileService_GetMe0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/users/me/profile", _ProfileService_UpdateProfile0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/users/me/avatar", _ProfileService_UpdateAvatar0_HTTP_Handler(srv))
}

func _ProfileService_GetMe0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetMe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMe(ctx, req.(*GetMeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserProfile)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserProfile)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateAvatar0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAvatarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateAvatar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAvatar(ctx, req.(*UpdateAvatarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserProfile)
		return ctx.Result(200, reply)
	}
}

type ProfileServiceHTTPClient interface {
	// GetMe 获取当前登录用户的账号信息和个人资料，用于“我的页面”展示。
	GetMe(ctx context.Context, req *GetMeRequest, opts ...http.CallOption) (rsp *UserProfile, err error)
	// UpdateAvatar 修改当前登录用户头像地址，并返回最新个人资料。
	UpdateAvatar(ctx context.Context, req *UpdateAvatarRequest, opts ...http.CallOption) (rsp *UserProfile, err error)
	// UpdateProfile 修改当前登录用户的个人资料，包括昵称、邮箱、生日、简介、地区等。
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *UserProfile, err error)
}

type ProfileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileServiceHTTPClient(client *http.Client) ProfileServiceHTTPClient {
	return &ProfileServiceHTTPClientImpl{client}
}

// GetMe 获取当前登录用户的账号信息和个人资料，用于“我的页面”展示。
func (c *ProfileServiceHTTPClientImpl) GetMe(ctx context.Context, in *GetMeRequest, opts ...http.CallOption) (*UserProfile, error) {
	var out UserProfile
	pattern := "/v1/users/me"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProfileServiceGetMe),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateAvatar 修改当前登录用户头像地址，并返回最新个人资料。
func (c *ProfileServiceHTTPClientImpl) UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...http.CallOption) (*UserProfile, error) {
	var out UserProfile
	pattern := "/v1/users/me/avatar"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProfileServiceUpdateAvatar),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateProfile 修改当前登录用户的个人资料，包括昵称、邮箱、生日、简介、地区等。
func (c *ProfileServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*UserProfile, error) {
	var out UserProfile
	pattern := "/v1/users/me/profile"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProfileServiceUpdateProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
