// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/v1/system.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAboutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAboutRequest) Reset() {
	*x = GetAboutRequest{}
	mi := &file_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAboutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAboutRequest) ProtoMessage() {}

func (x *GetAboutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAboutRequest.ProtoReflect.Descriptor instead.
func (*GetAboutRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{0}
}

type AboutInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PrivacyUrl    string                 `protobuf:"bytes,4,opt,name=privacy_url,json=privacyUrl,proto3" json:"privacy_url,omitempty"`
	TermsUrl      string                 `protobuf:"bytes,5,opt,name=terms_url,json=termsUrl,proto3" json:"terms_url,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Website       string                 `protobuf:"bytes,7,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AboutInfo) Reset() {
	*x = AboutInfo{}
	mi := &file_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AboutInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AboutInfo) ProtoMessage() {}

func (x *AboutInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AboutInfo.ProtoReflect.Descriptor instead.
func (*AboutInfo) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *AboutInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AboutInfo) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *AboutInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AboutInfo) GetPrivacyUrl() string {
	if x != nil {
		return x.PrivacyUrl
	}
	return ""
}

func (x *AboutInfo) GetTermsUrl() string {
	if x != nil {
		return x.TermsUrl
	}
	return ""
}

func (x *AboutInfo) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *AboutInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type ListPublicConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicConfigsRequest) Reset() {
	*x = ListPublicConfigsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicConfigsRequest) ProtoMessage() {}

func (x *ListPublicConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListPublicConfigsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{2}
}

type PublicConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicConfig) Reset() {
	*x = PublicConfig{}
	mi := &file_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicConfig) ProtoMessage() {}

func (x *PublicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicConfig.ProtoReflect.Descriptor instead.
func (*PublicConfig) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *PublicConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublicConfig) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *PublicConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListPublicConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*PublicConfig        `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicConfigsResponse) Reset() {
	*x = ListPublicConfigsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicConfigsResponse) ProtoMessage() {}

func (x *ListPublicConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListPublicConfigsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{4}
}

func (x *ListPublicConfigsResponse) GetConfigs() []*PublicConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type GetLatestVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestVersionRequest) Reset() {
	*x = GetLatestVersionRequest{}
	mi := &file_system_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestVersionRequest) ProtoMessage() {}

func (x *GetLatestVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestVersionRequest.ProtoReflect.Descriptor instead.
func (*GetLatestVersionRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestVersionRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type AppVersion struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform            string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Version             string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BuildNo             int32                  `protobuf:"varint,4,opt,name=build_no,json=buildNo,proto3" json:"build_no,omitempty"`
	ForceUpdate         bool                   `protobuf:"varint,5,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	DownloadUrl         string                 `protobuf:"bytes,6,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Changelog           string                 `protobuf:"bytes,7,opt,name=changelog,proto3" json:"changelog,omitempty"`
	MinSupportedVersion string                 `protobuf:"bytes,8,opt,name=min_supported_version,json=minSupportedVersion,proto3" json:"min_supported_version,omitempty"`
	PublishedAt         int64                  `protobuf:"varint,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AppVersion) Reset() {
	*x = AppVersion{}
	mi := &file_system_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppVersion) ProtoMessage() {}

func (x *AppVersion) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppVersion.ProtoReflect.Descriptor instead.
func (*AppVersion) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{6}
}

func (x *AppVersion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppVersion) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AppVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppVersion) GetBuildNo() int32 {
	if x != nil {
		return x.BuildNo
	}
	return 0
}

func (x *AppVersion) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *AppVersion) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *AppVersion) GetChangelog() string {
	if x != nil {
		return x.Changelog
	}
	return ""
}

func (x *AppVersion) GetMinSupportedVersion() string {
	if x != nil {
		return x.MinSupportedVersion
	}
	return ""
}

func (x *AppVersion) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

type ListAnnouncementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsRequest) Reset() {
	*x = ListAnnouncementsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsRequest) ProtoMessage() {}

func (x *ListAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{7}
}

func (x *ListAnnouncementsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type Announcement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TargetPlatform string                 `protobuf:"bytes,4,opt,name=target_platform,json=targetPlatform,proto3" json:"target_platform,omitempty"`
	StartAt        int64                  `protobuf:"varint,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt          int64                  `protobuf:"varint,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	mi := &file_system_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *Announcement) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Announcement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Announcement) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Announcement) GetTargetPlatform() string {
	if x != nil {
		return x.TargetPlatform
	}
	return ""
}

func (x *Announcement) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *Announcement) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type ListAnnouncementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Announcements []*Announcement        `protobuf:"bytes,1,rep,name=announcements,proto3" json:"announcements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsResponse) Reset() {
	*x = ListAnnouncementsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsResponse) ProtoMessage() {}

func (x *ListAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{9}
}

func (x *ListAnnouncementsResponse) GetAnnouncements() []*Announcement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

var File_system_v1_system_proto protoreflect.FileDescriptor

const file_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x16system/v1/system.proto\x12\tsystem.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fGetAboutRequest\"\xdf\x01\n" +
	"\tAboutInfo\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprivacy_url\x18\x04 \x01(\tR\n" +
	"privacyUrl\x12\x1b\n" +
	"\tterms_url\x18\x05 \x01(\tR\btermsUrl\x12#\n" +
	"\rcontact_email\x18\x06 \x01(\tR\fcontactEmail\x12\x18\n" +
	"\awebsite\x18\a \x01(\tR\awebsite\"\x1a\n" +
	"\x18ListPublicConfigsRequest\"a\n" +
	"\fPublicConfig\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"N\n" +
	"\x19ListPublicConfigsResponse\x121\n" +
	"\aconfigs\x18\x01 \x03(\v2\x17.system.v1.PublicConfigR\aconfigs\"5\n" +
	"\x17GetLatestVersionRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"\xa8\x02\n" +
	"\n" +
	"AppVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x19\n" +
	"\bbuild_no\x18\x04 \x01(\x05R\abuildNo\x12!\n" +
	"\fforce_update\x18\x05 \x01(\bR\vforceUpdate\x12!\n" +
	"\fdownload_url\x18\x06 \x01(\tR\vdownloadUrl\x12\x1c\n" +
	"\tchangelog\x18\a \x01(\tR\tchangelog\x122\n" +
	"\x15min_supported_version\x18\b \x01(\tR\x13minSupportedVersion\x12!\n" +
	"\fpublished_at\x18\t \x01(\x03R\vpublishedAt\"6\n" +
	"\x18ListAnnouncementsRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"\xa9\x01\n" +
	"\fAnnouncement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12'\n" +
	"\x0ftarget_platform\x18\x04 \x01(\tR\x0etargetPlatform\x12\x19\n" +
	"\bstart_at\x18\x05 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x06 \x01(\x03R\x05endAt\"Z\n" +
	"\x19ListAnnouncementsResponse\x12=\n" +
	"\rannouncements\x18\x01 \x03(\v2\x17.system.v1.AnnouncementR\rannouncements2\xe1\x03\n" +
	"\rSystemService\x12V\n" +
	"\bGetAbout\x12\x1a.system.v1.GetAboutRequest\x1a\x14.system.v1.AboutInfo\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/system/about\x12\x81\x01\n" +
	"\x11ListPublicConfigs\x12#.system.v1.ListPublicConfigsRequest\x1a$.system.v1.ListPublicConfigsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/system/configs/public\x12q\n" +
	"\x10GetLatestVersion\x12\".system.v1.GetLatestVersionRequest\x1a\x15.system.v1.AppVersion\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/system/versions/latest\x12\x80\x01\n" +
	"\x11ListAnnouncements\x12#.system.v1.ListAnnouncementsRequest\x1a$.system.v1.ListAnnouncementsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/system/announcementsB!Z\x1femo-ai-service/api/system/v1;v1b\x06proto3"

var (
	file_system_v1_system_proto_rawDescOnce sync.Once
	file_system_v1_system_proto_rawDescData []byte
)

func file_system_v1_system_proto_rawDescGZIP() []byte {
	file_system_v1_system_proto_rawDescOnce.Do(func() {
		file_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)))
	})
	return file_system_v1_system_proto_rawDescData
}

var file_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_system_v1_system_proto_goTypes = []any{
	(*GetAboutRequest)(nil),           // 0: system.v1.GetAboutRequest
	(*AboutInfo)(nil),                 // 1: system.v1.AboutInfo
	(*ListPublicConfigsRequest)(nil),  // 2: system.v1.ListPublicConfigsRequest
	(*PublicConfig)(nil),              // 3: system.v1.PublicConfig
	(*ListPublicConfigsResponse)(nil), // 4: system.v1.ListPublicConfigsResponse
	(*GetLatestVersionRequest)(nil),   // 5: system.v1.GetLatestVersionRequest
	(*AppVersion)(nil),                // 6: system.v1.AppVersion
	(*ListAnnouncementsRequest)(nil),  // 7: system.v1.ListAnnouncementsRequest
	(*Announcement)(nil),              // 8: system.v1.Announcement
	(*ListAnnouncementsResponse)(nil), // 9: system.v1.ListAnnouncementsResponse
}
var file_system_v1_system_proto_depIdxs = []int32{
	3, // 0: system.v1.ListPublicConfigsResponse.configs:type_name -> system.v1.PublicConfig
	8, // 1: system.v1.ListAnnouncementsResponse.announcements:type_name -> system.v1.Announcement
	0, // 2: system.v1.SystemService.GetAbout:input_type -> system.v1.GetAboutRequest
	2, // 3: system.v1.SystemService.ListPublicConfigs:input_type -> system.v1.ListPublicConfigsRequest
	5, // 4: system.v1.SystemService.GetLatestVersion:input_type -> system.v1.GetLatestVersionRequest
	7, // 5: system.v1.SystemService.ListAnnouncements:input_type -> system.v1.ListAnnouncementsRequest
	1, // 6: system.v1.SystemService.GetAbout:output_type -> system.v1.AboutInfo
	4, // 7: system.v1.SystemService.ListPublicConfigs:output_type -> system.v1.ListPublicConfigsResponse
	6, // 8: system.v1.SystemService.GetLatestVersion:output_type -> system.v1.AppVersion
	9, // 9: system.v1.SystemService.ListAnnouncements:output_type -> system.v1.ListAnnouncementsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_system_v1_system_proto_init() }
func file_system_v1_system_proto_init() {
	if File_system_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_system_proto_goTypes,
		DependencyIndexes: file_system_v1_system_proto_depIdxs,
		MessageInfos:      file_system_v1_system_proto_msgTypes,
	}.Build()
	File_system_v1_system_proto = out.File
	file_system_v1_system_proto_goTypes = nil
	file_system_v1_system_proto_depIdxs = nil
}
