// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: system/v1/system.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemService_GetAbout_FullMethodName          = "/system.v1.SystemService/GetAbout"
	SystemService_ListPublicConfigs_FullMethodName = "/system.v1.SystemService/ListPublicConfigs"
	SystemService_GetLatestVersion_FullMethodName  = "/system.v1.SystemService/GetLatestVersion"
	SystemService_ListAnnouncements_FullMethodName = "/system.v1.SystemService/ListAnnouncements"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	// 获取关于我们信息，包括应用介绍、协议链接和联系方式。
	GetAbout(ctx context.Context, in *GetAboutRequest, opts ...grpc.CallOption) (*AboutInfo, error)
	// 查询前端可公开读取的系统配置。
	ListPublicConfigs(ctx context.Context, in *ListPublicConfigsRequest, opts ...grpc.CallOption) (*ListPublicConfigsResponse, error)
	// 查询指定平台最新版本和更新策略。
	GetLatestVersion(ctx context.Context, in *GetLatestVersionRequest, opts ...grpc.CallOption) (*AppVersion, error)
	// 查询当前平台有效期内的系统公告。
	ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetAbout(ctx context.Context, in *GetAboutRequest, opts ...grpc.CallOption) (*AboutInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AboutInfo)
	err := c.cc.Invoke(ctx, SystemService_GetAbout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListPublicConfigs(ctx context.Context, in *ListPublicConfigsRequest, opts ...grpc.CallOption) (*ListPublicConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicConfigsResponse)
	err := c.cc.Invoke(ctx, SystemService_ListPublicConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetLatestVersion(ctx context.Context, in *GetLatestVersionRequest, opts ...grpc.CallOption) (*AppVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppVersion)
	err := c.cc.Invoke(ctx, SystemService_GetLatestVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAnnouncementsResponse)
	err := c.cc.Invoke(ctx, SystemService_ListAnnouncements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
type SystemServiceServer interface {
	// 获取关于我们信息，包括应用介绍、协议链接和联系方式。
	GetAbout(context.Context, *GetAboutRequest) (*AboutInfo, error)
	// 查询前端可公开读取的系统配置。
	ListPublicConfigs(context.Context, *ListPublicConfigsRequest) (*ListPublicConfigsResponse, error)
	// 查询指定平台最新版本和更新策略。
	GetLatestVersion(context.Context, *GetLatestVersionRequest) (*AppVersion, error)
	// 查询当前平台有效期内的系统公告。
	ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) GetAbout(context.Context, *GetAboutRequest) (*AboutInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAbout not implemented")
}
func (UnimplementedSystemServiceServer) ListPublicConfigs(context.Context, *ListPublicConfigsRequest) (*ListPublicConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicConfigs not implemented")
}
func (UnimplementedSystemServiceServer) GetLatestVersion(context.Context, *GetLatestVersionRequest) (*AppVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestVersion not implemented")
}
func (UnimplementedSystemServiceServer) ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAnnouncements not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_GetAbout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAboutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetAbout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetAbout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetAbout(ctx, req.(*GetAboutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListPublicConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListPublicConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_ListPublicConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListPublicConfigs(ctx, req.(*ListPublicConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetLatestVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetLatestVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetLatestVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetLatestVersion(ctx, req.(*GetLatestVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnnouncementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_ListAnnouncements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListAnnouncements(ctx, req.(*ListAnnouncementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.v1.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAbout",
			Handler:    _SystemService_GetAbout_Handler,
		},
		{
			MethodName: "ListPublicConfigs",
			Handler:    _SystemService_ListPublicConfigs_Handler,
		},
		{
			MethodName: "GetLatestVersion",
			Handler:    _SystemService_GetLatestVersion_Handler,
		},
		{
			MethodName: "ListAnnouncements",
			Handler:    _SystemService_ListAnnouncements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/v1/system.proto",
}
