// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: emotion/v1/emotion.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmotionService_CreateAnalysis_FullMethodName = "/emotion.v1.EmotionService/CreateAnalysis"
	EmotionService_ListAnalyses_FullMethodName   = "/emotion.v1.EmotionService/ListAnalyses"
	EmotionService_GetAnalysis_FullMethodName    = "/emotion.v1.EmotionService/GetAnalysis"
	EmotionService_GetOverview_FullMethodName    = "/emotion.v1.EmotionService/GetOverview"
	EmotionService_GetTrends_FullMethodName      = "/emotion.v1.EmotionService/GetTrends"
	EmotionService_GetCalendar_FullMethodName    = "/emotion.v1.EmotionService/GetCalendar"
)

// EmotionServiceClient is the client API for EmotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmotionServiceClient interface {
	// 对文本创建情绪分析结果，保存情绪、风险、建议和维度分数。
	CreateAnalysis(ctx context.Context, in *CreateAnalysisRequest, opts ...grpc.CallOption) (*EmotionAnalysis, error)
	// 分页查询当前用户的情绪分析历史。
	ListAnalyses(ctx context.Context, in *ListAnalysesRequest, opts ...grpc.CallOption) (*ListAnalysesResponse, error)
	// 获取指定情绪分析详情。
	GetAnalysis(ctx context.Context, in *GetAnalysisRequest, opts ...grpc.CallOption) (*EmotionAnalysis, error)
	// 获取情感分析报告总览统计。
	GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*EmotionOverview, error)
	// 获取情绪趋势折线图数据。
	GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*EmotionTrends, error)
	// 获取情绪日历视图数据。
	GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*EmotionCalendar, error)
}

type emotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmotionServiceClient(cc grpc.ClientConnInterface) EmotionServiceClient {
	return &emotionServiceClient{cc}
}

func (c *emotionServiceClient) CreateAnalysis(ctx context.Context, in *CreateAnalysisRequest, opts ...grpc.CallOption) (*EmotionAnalysis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionAnalysis)
	err := c.cc.Invoke(ctx, EmotionService_CreateAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionServiceClient) ListAnalyses(ctx context.Context, in *ListAnalysesRequest, opts ...grpc.CallOption) (*ListAnalysesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAnalysesResponse)
	err := c.cc.Invoke(ctx, EmotionService_ListAnalyses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionServiceClient) GetAnalysis(ctx context.Context, in *GetAnalysisRequest, opts ...grpc.CallOption) (*EmotionAnalysis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionAnalysis)
	err := c.cc.Invoke(ctx, EmotionService_GetAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionServiceClient) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*EmotionOverview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionOverview)
	err := c.cc.Invoke(ctx, EmotionService_GetOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionServiceClient) GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*EmotionTrends, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionTrends)
	err := c.cc.Invoke(ctx, EmotionService_GetTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionServiceClient) GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*EmotionCalendar, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionCalendar)
	err := c.cc.Invoke(ctx, EmotionService_GetCalendar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmotionServiceServer is the server API for EmotionService service.
// All implementations must embed UnimplementedEmotionServiceServer
// for forward compatibility.
type EmotionServiceServer interface {
	// 对文本创建情绪分析结果，保存情绪、风险、建议和维度分数。
	CreateAnalysis(context.Context, *CreateAnalysisRequest) (*EmotionAnalysis, error)
	// 分页查询当前用户的情绪分析历史。
	ListAnalyses(context.Context, *ListAnalysesRequest) (*ListAnalysesResponse, error)
	// 获取指定情绪分析详情。
	GetAnalysis(context.Context, *GetAnalysisRequest) (*EmotionAnalysis, error)
	// 获取情感分析报告总览统计。
	GetOverview(context.Context, *GetOverviewRequest) (*EmotionOverview, error)
	// 获取情绪趋势折线图数据。
	GetTrends(context.Context, *GetTrendsRequest) (*EmotionTrends, error)
	// 获取情绪日历视图数据。
	GetCalendar(context.Context, *GetCalendarRequest) (*EmotionCalendar, error)
	mustEmbedUnimplementedEmotionServiceServer()
}

// UnimplementedEmotionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmotionServiceServer struct{}

func (UnimplementedEmotionServiceServer) CreateAnalysis(context.Context, *CreateAnalysisRequest) (*EmotionAnalysis, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAnalysis not implemented")
}
func (UnimplementedEmotionServiceServer) ListAnalyses(context.Context, *ListAnalysesRequest) (*ListAnalysesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAnalyses not implemented")
}
func (UnimplementedEmotionServiceServer) GetAnalysis(context.Context, *GetAnalysisRequest) (*EmotionAnalysis, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalysis not implemented")
}
func (UnimplementedEmotionServiceServer) GetOverview(context.Context, *GetOverviewRequest) (*EmotionOverview, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverview not implemented")
}
func (UnimplementedEmotionServiceServer) GetTrends(context.Context, *GetTrendsRequest) (*EmotionTrends, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrends not implemented")
}
func (UnimplementedEmotionServiceServer) GetCalendar(context.Context, *GetCalendarRequest) (*EmotionCalendar, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCalendar not implemented")
}
func (UnimplementedEmotionServiceServer) mustEmbedUnimplementedEmotionServiceServer() {}
func (UnimplementedEmotionServiceServer) testEmbeddedByValue()                        {}

// UnsafeEmotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmotionServiceServer will
// result in compilation errors.
type UnsafeEmotionServiceServer interface {
	mustEmbedUnimplementedEmotionServiceServer()
}

func RegisterEmotionServiceServer(s grpc.ServiceRegistrar, srv EmotionServiceServer) {
	// If the following call panics, it indicates UnimplementedEmotionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmotionService_ServiceDesc, srv)
}

func _EmotionService_CreateAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).CreateAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_CreateAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).CreateAnalysis(ctx, req.(*CreateAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionService_ListAnalyses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnalysesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).ListAnalyses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_ListAnalyses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).ListAnalyses(ctx, req.(*ListAnalysesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionService_GetAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).GetAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_GetAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).GetAnalysis(ctx, req.(*GetAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionService_GetOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).GetOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_GetOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).GetOverview(ctx, req.(*GetOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionService_GetTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).GetTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_GetTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).GetTrends(ctx, req.(*GetTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionService_GetCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).GetCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_GetCalendar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).GetCalendar(ctx, req.(*GetCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmotionService_ServiceDesc is the grpc.ServiceDesc for EmotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion.v1.EmotionService",
	HandlerType: (*EmotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAnalysis",
			Handler:    _EmotionService_CreateAnalysis_Handler,
		},
		{
			MethodName: "ListAnalyses",
			Handler:    _EmotionService_ListAnalyses_Handler,
		},
		{
			MethodName: "GetAnalysis",
			Handler:    _EmotionService_GetAnalysis_Handler,
		},
		{
			MethodName: "GetOverview",
			Handler:    _EmotionService_GetOverview_Handler,
		},
		{
			MethodName: "GetTrends",
			Handler:    _EmotionService_GetTrends_Handler,
		},
		{
			MethodName: "GetCalendar",
			Handler:    _EmotionService_GetCalendar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emotion/v1/emotion.proto",
}
