// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: emotion/v1/emotion.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationEmotionServiceCreateAnalysis = "/emotion.v1.EmotionService/CreateAnalysis"
const OperationEmotionServiceGetAnalysis = "/emotion.v1.EmotionService/GetAnalysis"
const OperationEmotionServiceGetCalendar = "/emotion.v1.EmotionService/GetCalendar"
const OperationEmotionServiceGetOverview = "/emotion.v1.EmotionService/GetOverview"
const OperationEmotionServiceGetTrends = "/emotion.v1.EmotionService/GetTrends"
const OperationEmotionServiceListAnalyses = "/emotion.v1.EmotionService/ListAnalyses"

type EmotionServiceHTTPServer interface {
	// CreateAnalysis 对文本创建情绪分析结果，保存情绪、风险、建议和维度分数。
	CreateAnalysis(context.Context, *CreateAnalysisRequest) (*EmotionAnalysis, error)
	// GetAnalysis 获取指定情绪分析详情。
	GetAnalysis(context.Context, *GetAnalysisRequest) (*EmotionAnalysis, error)
	// GetCalendar 获取情绪日历视图数据。
	GetCalendar(context.Context, *GetCalendarRequest) (*EmotionCalendar, error)
	// GetOverview 获取情感分析报告总览统计。
	GetOverview(context.Context, *GetOverviewRequest) (*EmotionOverview, error)
	// GetTrends 获取情绪趋势折线图数据。
	GetTrends(context.Context, *GetTrendsRequest) (*EmotionTrends, error)
	// ListAnalyses 分页查询当前用户的情绪分析历史。
	ListAnalyses(context.Context, *ListAnalysesRequest) (*ListAnalysesResponse, error)
}

func RegisterEmotionServiceHTTPServer(s *http.Server, srv EmotionServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/emotion/analyses", _EmotionService_CreateAnalysis0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/emotion/analyses", _EmotionService_ListAnalyses0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/emotion/analyses/{id}", _EmotionService_GetAnalysis0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/emotion/reports/overview", _EmotionService_GetOverview0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/emotion/reports/trends", _EmotionService_GetTrends0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/emotion/reports/calendar", _EmotionService_GetCalendar0_HTTP_Handler(srv))
}

func _EmotionService_CreateAnalysis0_HTTP_Handler(srv EmotionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAnalysisRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmotionServiceCreateAnalysis)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAnalysis(ctx, req.(*CreateAnalysisRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmotionAnalysis)
		return ctx.Result(200, reply)
	}
}

func _EmotionService_ListAnalyses0_HTTP_Handler(srv EmotionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAnalysesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmotionServiceListAnalyses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAnalyses(ctx, req.(*ListAnalysesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAnalysesResponse)
		return ctx.Result(200, reply)
	}
}

func _EmotionService_GetAnalysis0_HTTP_Handler(srv EmotionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAnalysisRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmotionServiceGetAnalysis)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAnalysis(ctx, req.(*GetAnalysisRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmotionAnalysis)
		return ctx.Result(200, reply)
	}
}

func _EmotionService_GetOverview0_HTTP_Handler(srv EmotionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOverviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmotionServiceGetOverview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOverview(ctx, req.(*GetOverviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmotionOverview)
		return ctx.Result(200, reply)
	}
}

func _EmotionService_GetTrends0_HTTP_Handler(srv EmotionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTrendsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmotionServiceGetTrends)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTrends(ctx, req.(*GetTrendsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmotionTrends)
		return ctx.Result(200, reply)
	}
}

func _EmotionService_GetCalendar0_HTTP_Handler(srv EmotionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCalendarRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmotionServiceGetCalendar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCalendar(ctx, req.(*GetCalendarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmotionCalendar)
		return ctx.Result(200, reply)
	}
}

type EmotionServiceHTTPClient interface {
	// CreateAnalysis 对文本创建情绪分析结果，保存情绪、风险、建议和维度分数。
	CreateAnalysis(ctx context.Context, req *CreateAnalysisRequest, opts ...http.CallOption) (rsp *EmotionAnalysis, err error)
	// GetAnalysis 获取指定情绪分析详情。
	GetAnalysis(ctx context.Context, req *GetAnalysisRequest, opts ...http.CallOption) (rsp *EmotionAnalysis, err error)
	// GetCalendar 获取情绪日历视图数据。
	GetCalendar(ctx context.Context, req *GetCalendarRequest, opts ...http.CallOption) (rsp *EmotionCalendar, err error)
	// GetOverview 获取情感分析报告总览统计。
	GetOverview(ctx context.Context, req *GetOverviewRequest, opts ...http.CallOption) (rsp *EmotionOverview, err error)
	// GetTrends 获取情绪趋势折线图数据。
	GetTrends(ctx context.Context, req *GetTrendsRequest, opts ...http.CallOption) (rsp *EmotionTrends, err error)
	// ListAnalyses 分页查询当前用户的情绪分析历史。
	ListAnalyses(ctx context.Context, req *ListAnalysesRequest, opts ...http.CallOption) (rsp *ListAnalysesResponse, err error)
}

type EmotionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEmotionServiceHTTPClient(client *http.Client) EmotionServiceHTTPClient {
	return &EmotionServiceHTTPClientImpl{client}
}

// CreateAnalysis 对文本创建情绪分析结果，保存情绪、风险、建议和维度分数。
func (c *EmotionServiceHTTPClientImpl) CreateAnalysis(ctx context.Context, in *CreateAnalysisRequest, opts ...http.CallOption) (*EmotionAnalysis, error) {
	var out EmotionAnalysis
	pattern := "/v1/emotion/analyses"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationEmotionServiceCreateAnalysis),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAnalysis 获取指定情绪分析详情。
func (c *EmotionServiceHTTPClientImpl) GetAnalysis(ctx context.Context, in *GetAnalysisRequest, opts ...http.CallOption) (*EmotionAnalysis, error) {
	var out EmotionAnalysis
	pattern := "/v1/emotion/analyses/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEmotionServiceGetAnalysis),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCalendar 获取情绪日历视图数据。
func (c *EmotionServiceHTTPClientImpl) GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...http.CallOption) (*EmotionCalendar, error) {
	var out EmotionCalendar
	pattern := "/v1/emotion/reports/calendar"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEmotionServiceGetCalendar),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetOverview 获取情感分析报告总览统计。
func (c *EmotionServiceHTTPClientImpl) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...http.CallOption) (*EmotionOverview, error) {
	var out EmotionOverview
	pattern := "/v1/emotion/reports/overview"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEmotionServiceGetOverview),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTrends 获取情绪趋势折线图数据。
func (c *EmotionServiceHTTPClientImpl) GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...http.CallOption) (*EmotionTrends, error) {
	var out EmotionTrends
	pattern := "/v1/emotion/reports/trends"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEmotionServiceGetTrends),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAnalyses 分页查询当前用户的情绪分析历史。
func (c *EmotionServiceHTTPClientImpl) ListAnalyses(ctx context.Context, in *ListAnalysesRequest, opts ...http.CallOption) (*ListAnalysesResponse, error) {
	var out ListAnalysesResponse
	pattern := "/v1/emotion/analyses"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEmotionServiceListAnalyses),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
